### ISSUE TITLE
Cant use the module on Linux Mint

### ISSUE THREAD

**Issue by nathandtrone** [websockets/ws#1008]
I've tried it on different systems, and it only seems to happen on Linux Mint.
Is this something I can fix without having to modify the OS or the Module itself?

Error Info:

/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<MAIN>:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by lpinca** [comment]
If you are using `ws@2` you need Node.js 4.5.0 or greater.

**Comment by YtvwlD** [comment]
I'm getting the same error:
```
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ytvwld/quassel-webserver/node_modules/net-browserify-alt/api.js:6:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

```
$ node -v
v0.10.43
```
