### ISSUE TITLE
Can't run the simplest server example from README

### ISSUE THREAD

**Issue by pyrorules** [websockets/ws#1013]
So i'm trying to run the following code (from README):

```
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});
```

But it returns the following error:

```
pyro@pyro-MS-7816:~/node-training$ node main.js 
/home/pyro/node-training/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/pyro/node-training/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pyro/node-training/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

How to make it work?
```

**Comment by pyrorules** [comment]
If you get a similar problem just update your Node.js
