### ISSUE TITLE
v2.2.1 has broken linter

### ISSUE THREAD

**Issue by MylesBorins** [websockets/ws#1050]
```
       > ws@2.2.1 test /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws
 > npm run lint && mocha test/*.test.js
 > ws@2.2.1 lint /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws
 > eslint .
 standard:
 	Configuration for rule "no-unused-expressions" is invalid:
 	Value "data["0"].allowTaggedTemplates" has additional properties.
 Referenced from: /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/.eslintrc.yaml
 Error: standard:
 	Configuration for rule "no-unused-expressions" is invalid:
 	Value "data["0"].allowTaggedTemplates" has additional properties.
 Referenced from: /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/.eslintrc.yaml
     at validateRuleOptions (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-validator.js:109:15)
     at /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-validator.js:156:13
     at Array.forEach (native)
     at Object.validate (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-validator.js:155:35)
     at load (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-file.js:529:19)
     at /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-file.js:391:36
     at Array.reduceRight (native)
     at applyExtends (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-file.js:362:28)
     at Object.load (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config/config-file.js:536:22)
     at loadConfig (/private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/node_modules/eslint/lib/config.js:63:33)
 npm ERR! Darwin 14.5.0
 npm ERR! argv "/Users/iojs/build/workspace/citgm-smoker/nodes/osx1010/smoker/bin/node" "/Users/iojs/build/workspace/citgm-smoker/nodes/osx1010/smoker/bin/npm" "run" "lint"
 npm ERR! node v4.8.1
 npm ERR! npm  v2.15.11
 npm ERR! code ELIFECYCLE
 npm ERR! ws@2.2.1 lint: `eslint .`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the ws@2.2.1 lint script 'eslint .'.
 npm ERR! This is most likely a problem with the ws package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     eslint .
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs ws
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR! 
 npm ERR!     npm owner ls ws
 npm ERR! There is likely additional logging output above.
 npm ERR! Please include the following file with any support request:
 npm ERR!     /private/var/folders/28/x1nl9rs561g1xdq6mk0jgkp80000gp/T/24bc4afe-f63c-4533-964f-8ee7fbabb10a/ws/npm-debug.log
 npm ERR! Test failed.  See above for more details.
```

**Comment by lpinca** [comment]
This is weird as the [build](https://travis-ci.org/websockets/ws/builds/210459994) passed on Travis but I can reproduce locally on macOS.

It seems to work with the latest version of eslint.
I'll cut a new release later to unbreak CITGM.

Thanks Myles.

**Comment by chemitaxis** [comment]
I have the same error...
