### ISSUE TITLE
autobahn 0.9.9

### ISSUE THREAD

**Issue by sese** [websockets/ws#1115]
After you released the 3.0.0 version autobahn use it as dependency and our crossbar application failed to start. I got this errors:
```
 /home/sese/app/node_modules/autobahn/lib/transport/websocket.js:99
 if (flags.binary) {
 ^
 TypeError: Cannot read property 'binary' of undefined
 at WebSocket.<anonymous> (/home/sese/app/node_modules/autobahn/lib/transport/websocket.js:99:22)
 at emitOne (events.js:96:13)
 at WebSocket.emit (events.js:188:7)
 at Receiver._receiver.onmessage (/home/sese/app/node_modules/ws/lib/WebSocket.js:146:47)
 at Receiver.dataMessage (/home/sese/app/node_modules/ws/lib/Receiver.js:389:14)
 at Receiver.getData (/home/sese/app/node_modules/ws/lib/Receiver.js:330:12)
 at Receiver.startLoop (/home/sese/app/node_modules/ws/lib/Receiver.js:165:16)
 at Receiver.add (/home/sese/app/node_modules/ws/lib/Receiver.js:139:10)
 at Socket._ultron.on (/home/sese/app/node_modules/ws/lib/WebSocket.js:142:22)
 at emitOne (events.js:96:13)
 at Socket.emit (events.js:188:7)
 at readableAddChunk (_stream_readable.js:176:18)
 at Socket.Readable.push (_stream_readable.js:134:10)
 at TCP.onread (net.js:551:20)
 Guest worker-002 exited with error A process has ended with a probable error condition: process ended with exit code 1.
```

And this error points to websocket.js:99:

```
websocket.on('message', function (data, flags) {
    if (flags.binary) {
        // FIXME!
    } else {  
        var msg = JSON.parse(data);
        transport.onmessage(msg);
    }
});
```

I suppose there are some unfinished code. We spent more than 6 hours, 4 developers to find something wrong in our application, we rollback commits from 3 repositories until we found this unexpected versioning issue. Please fix.

**Comment by lpinca** [comment]
It is not a good idea to use this https://github.com/crossbario/autobahn-js/blob/c306584652eb1e94521de9426c800c8579e1a52c/package.json#L19. You reported the issue in the wrong repo.

We use semver versioning for a reason. I'm sorry for all the time you wasted on this :(

**Comment by sese** [comment]
You have right, the issue was hiding behind another issue in autobahn package.json dependencies. We saw that and we added proper package version for ws (2.3.1) in our package.json. But still you have an issue in your code, you should throw an exception instead that comment that tells nothing from my perspective and shows that it's unfinished. You have a huge responsibility not only for your code but also for all other modules that use your library.

**Comment by lpinca** [comment]
FYI that comment is in autobahn-js not ws: https://github.com/crossbario/autobahn-js/blob/ac254578644d7e0fcfd38ed8867f94481bd806c5/package/lib/transport/websocket.js#L99.

**Comment by sese** [comment]
You are right. Sorry for comment, I'll open an issue to autobahn.
