### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by Zane96** [websockets/ws#1133]
#### Description

I use ws in a WebSocket Demo, but there always show this error:Error: connect ECONNREFUSED 127.0.0.1:3001
```
Error: connect ECONNREFUSED 127.0.0.1:3001
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
```
#### Reproducible in:

version: 1.1.1
Node.js version(s): 7.0.1
OS version(s): Mac OSX

```
const WebSocket = require('ws');

const WebSocketServer = WebSocket.Server;

const wss = new WebSocketServer({
    port: 3001
});

wss.on('connection', function (ws) {
    console.log(`[SERVER] connection()`);
    ws.on('message', function (message) {
        console.log(`[SERVER] Received: ${message}`);
        setTimeout(() => {
            ws.send(`What's your name?`, (err) => {
                if (err) {
                    console.log(`[SERVER] error: ${err}`);
                }
            });
        }, 1000);
    })
});

console.log('ws server started at port 3001...');

// client test:

let count = 0;

let ws = new WebSocket('ws://127.0.0.1:3001/ws/chat');

ws.on('open', function () {
    console.log(`[CLIENT] open()`);
    ws.send('Hello!');
});

ws.on('message', function (message) {
    console.log(`[CLIENT] Received: ${message}`);
    count++;
    if (count > 3) {
        ws.send('Goodbye!');
        ws.close();
    } else {
        setTimeout(() => {
            ws.send(`Hello, I'm Mr No.${count}!`);
        }, 1000);
    }
});
```

**Comment by Zane96** [comment]
It seems like the error is when client try to connect server

**Comment by Zane96** [comment]
OS Version: macOS Sierra

**Comment by Zane96** [comment]
em....
I found the laste release is 3.0.0.
I fixed it by upgrade the ws to 3.0.0

**Comment by lpinca** [comment]
The example you posted also works with ws@1.1.1 on my machine, closing.

**Comment by Zane96** [comment]
。。。fine
