### ISSUE TITLE
Error Not Opnend

### ISSUE THREAD

**Issue by quesurifn** [websockets/ws#1164]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Error not opened after 10 - 20 page refreshes. All messages will be crippled until server is rebooted

#### Reproducible in:

version: Edge
Node.js version(s): 8.1.3
OS version(s): Mac OSX Sierra

#### Steps to reproduce:

```js
'use strict';

// Include the cluster module
var cluster = require('cluster');

// Code to run if we're in the master process
if (cluster.isMaster) {

    // Count the machine's CPUs
    var cpuCount = require('os').cpus().length;

    // Create a worker for each CPU
    for (var i = 0; i < cpuCount; i += 1) {
        cluster.fork();
    }

    // Listen for dying workers
    cluster.on('exit', function (worker) {

        // Replace the dead worker, we're not sentimental
        console.log('Worker %d died :(', worker.id);
        cluster.fork();

    });

// Code to run if we're in a worker process
} else {

    const express = require('express');
    const app = express();
    const http = require('http')
    const Twit = require('twit')
    const sentiment = require('sentiment');
    const WebSocket = require('ws');
    const port = process.env.PORT || 3000;
    const cluster = require('cluster');
    require('dotenv').config()

    const server = http.createServer(app);
    const wss = new WebSocket.Server({ server });

    const T = new Twit({
      consumer_key:         process.env.TWITTER_CONSUMER_KEY,
      consumer_secret:      process.env.TWITTER_CONSUMER_SECRET,
      access_token:         process.env.TWITTER_ACCESS_TOKEN,
      access_token_secret:  process.env.TWITTER_ACCESS_SECRET,
    }) 


    app.use(function(req, res, next) {
      res.header("Access-Control-Allow-Origin", "*");
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
      next();
    });


    app.get('/', function(req, res) {
      res.send('Congratulations, you sent a GET request!');
      console.log('Received a GET request and sent a response');
    });


    function heartbeat() {
      console.log('heartbeat')
      this.isAlive = true;
    }

    wss.on('connection', function(ws, req) {
      
      ws.isAlive = true;
      ws.on('pong', heartbeat);


      // Variables outside of stream
      let streamedTweets = [];
      let tweetsWithLoc =[];
      let pos = 0;
      let neu = 0;
      let neg = 0;
      let scoreArray = [];
      let scoreArrayLength = 0;
      let average = 0;

      const stream = T.stream('statuses/filter', { track: ['POTUS', 'trump', 'president', 'realDonaldTrump'], locations: '-180,-90,180,90', language: 'en' })
      stream.on('tweet', function(tweet) {
        let individualSent = sentiment(tweet.text)
        
        if (individualSent.score > 0) {
          pos++
        } else if (individualSent.score < 0) {
          neg++
        } else if (individualSent.score === 0) {
          neu++
        }

        if (individualSent.score > 0) {
          scoreArray.push(individualSent.score)
        } else if (individualSent.score < 0) {
          scoreArray.push(individualSent.score * 1.35)
        }
        // push tweets to array
        streamedTweets.push(tweet.text)

        //Tweet location

        // if tweet has cooridnates
        if(tweet.coordinates) {
          //and if coordiantes don't = null
          if(tweet.coordinates != null) {
              
              //get location sentiment and lng / lat
              let outputPoint = {"lat": tweet.coordinates.coordinates[0],"lng": tweet.coordinates.coordinates[1]};
              let locSentiment = sentiment(tweet.text)

              // push to the location array 
              tweetsWithLoc.push({"tweet": tweet.text, "location": outputPoint, "sentiment": locSentiment});
          }
        }

        // When there are 40 tweets push to client
        if(tweetsWithLoc.length === 40) {

          try { 
            ws.send(JSON.stringify({"location":tweetsWithLoc})) 
          } catch(e) {
            console.log(e)
          }

        // resset array
        tweetsWithLoc.length = 0;
        }

        //send streamed tweets off when the array hits 50 tweets
        if(streamedTweets.length === 50) { 

          scoreArrayLength = scoreArray.length
          average = scoreArray.reduce((a, b) => a + b, 0);
          average = average / scoreArrayLength;

          average = average.toFixed(4);

          average = parseFloat(average)

          //join all the tweets in the array to a single string
          let trumpSentiment = sentiment(streamedTweets.join());
        

          // FIRE!!
          try {          
            ws.send(JSON.stringify({"main": {"sentiment": trumpSentiment, "featuredTweet": streamedTweets[19], "pos": pos, "neg": neg, "neu": neu, "average": average}}))
          } catch(e) {
            console.log(e)
          }
            
          //clear array & start over
          scoreArrayLength = 0;
          scoreArray.length = 0;
          streamedTweets.length = 0;
          pos = 0
          neg = 0
          neu = 0
        }
      })

      ws.on('close', function () {
        stream.stop();
      });

    })


    // clean up connection
    const interval = setInterval(function ping() {
      wss.clients.forEach(function each(ws) {
        if (ws.isAlive === false) return ws.terminate();

        ws.isAlive = false;
        ws.ping('', false, true);
      });
    }, 1000);


  server.listen(port, function listening() {
    console.log('Listening on %d', server.address().port);
  });

}
```

### Expected result:

No error

### Actual result:

The stack trace

```
Error: not opened 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:358:18) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at StreamingAPIConnection.<anonymous> (/app/app.js:150:16) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at emitOne (events.js:115:13) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at StreamingAPIConnection.emit (events.js:210:7) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at module.exports.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:319:56) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at emitOne (events.js:115:13) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at module.exports.emit (events.js:210:7) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at module.exports.Parser.parse (/app/node_modules/twit/lib/parser.js:47:16) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at Gunzip.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:139:21) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at emitOne (events.js:115:13) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at Gunzip.emit (events.js:210:7) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at addChunk (_stream_readable.js:252:12) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at readableAddChunk (_stream_readable.js:239:11) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at Gunzip.Readable.push (_stream_readable.js:197:10) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at Gunzip.Transform.push (_stream_transform.js:151:32) 
Jul 04 16:17:03 trump-sentiment app/web.1: 4|app      |     at Zlib.callback (zlib.js:444:14) 
```

I'm reopening because the solution you offered fixes for longer amount of time but issue still happens. In other issues, other suggest not throwing an error on the server side.

**Comment by lpinca** [comment]
> after 10 - 20 page refreshes

By doing this you basically close and reopen a new Twitter stream every time. Clients that make excessive connections attempts are rated limited by Twitter: https://dev.twitter.com/streaming/public.

When you get rate limited `twit` tries to [`reconnect`](https://github.com/ttezel/twit#event-reconnect). You can track this by adding a listener for the `'reconnect'` event.

When reconnection happens the Twitter stream writes to a previously closed WebSocket object and as expected you get the error.

This is basically why in the previous issue I warned you that using a new Twitter stream for each WebSocket connection is not a good idea.

Again this isn't an issue in `ws` as it is working as expected.

**Comment by shellscape** [comment]
@lpinca I think this one might have been a premature close. While the situation I'm facing is different, I've been getting the same error approximately once for every 20 new socket servers created. I'm one of the active maintainers of webpack-dev-server and have been refactoring away from SockJS to ws. While the frequency of this error is pretty low, it _does_ happen, and it _is an issue_ somewhere within the library.

![Imgur](https://i.imgur.com/AdJ4m1x.png)

From what I can tell, this is some kind of concurrency/race issue. Here's our present block that handles the `connection` event for the server, and wires up some convenience methods:

```js
      wss.on('connection', (ws) => {
        this.socket = ws;
        this.socket.payload = payload;

        function payload(type, data) {
          return JSON.stringify({ type, data });
        }

        const originalSend = ws.send;

        ws.send = function send() {
          const args = Array.prototype.slice.call(arguments);
          log.debug('ws.send:', args);
          originalSend.apply(ws, args);
        };

        ws.send(payload('options', this.options));

        if (this.stats) {
          sendStats(this.socket, {
            force: true,
            stats: this.stats.toJson(this.options.clientStats)
          });
        }
      });

      if (callback) {
        callback.call(this.server, err);
      }
    });
```

At first we thought it was an issue with the proxying of `socket.send`, as they error was occurring in the same place at `originalSend.apply(ws, args);` every time. So we removed the proxy and the stack shifted back into the `ws` for each error, meaning the proxying had no effect. 

It would then seem that some kind of concurrency issue whereby the socket is created and available in the `connection` event, but doesn't think it's yet "open." We're going to trap the error and retry the `send` after a tick to see if that clears up the error, but it's absolutely something that happens on a somewhat regular basis for us.

**Comment by lpinca** [comment]
@shellscape are you able to create a test case to reproduce the issue?

> It would then seem that some kind of concurrency issue whereby the socket is created and available in the connection event, but doesn't think it's yet "open."

If you write on the same tick of the 'connection' event it shound't be possible. If you write later you should check that `ws.readyState === WebSocket.OPEN`.

**Comment by shellscape** [comment]
@lpinca I might be able to put together a test app that reproduces; it'd likely be a combo of express, http, and ws. but you'd have to be open to a reproducible, yet not consistent result set. given the nature of the frequency of this, I doubt you'd get the same number of failures at the same time for each run.

We'll implement that `readyState` check and see how that goes. We're not seeing any `close` events on the WebSocket server, but I suppose it's entirely possible that the `send` happens before `close` is sent, perhaps while the state is in `CLOSING`

**Comment by lpinca** [comment]
@shellscape that's fine as long as it reproduces.
