### ISSUE TITLE
Error: write ECANCELED

### ISSUE THREAD

**Issue by KyKyIIIKuH** [websockets/ws#1192]
When the server is running for more than 2 hours, the following error occurs:
```
    events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write ECANCELED
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:851:14)
```
The server uses the wss protocol:
```
var fs = require('fs');
var https = require ('https');
var express = require('express');

var options = {
    key: fs.readFileSync('ssl/ploa/key.pem', 'utf8'),
    cert: fs.readFileSync('ssl/ploa/cert.pem', 'utf8')
};

var Application = express();
var Server = https.createServer(options, Application);

Server.listen(8443);

// create server
var WebSocketServer = require('ws').Server,
    wss = new WebSocketServer({server: Server});
```

How to fix / handle this problem so that this error does not appear again?

**Comment by lpinca** [comment]
Not sure why this error happens but there are other network errors that can happen. You have to add a listener for the `'error'` event.

```js
ws.on('error', (err) => handleError(err));
```
