### ISSUE TITLE
node_modules\autobahn\lib\transport\websocket.js:99

### ISSUE THREAD

**Issue by leonidasgomes** [websockets/ws#1263]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

version:
Node.js version(s):
OS version(s):

#### Steps to reproduce:

1.
2.
3.

### Attachments:

TypeError: Cannot read property 'binary' of undefined
    at WebSocket.<anonymous> (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\autobahn\lib\transport\websocket.js:99:23)
    at WebSocket.emit (events.js:159:13)
    at Receiver._receiver.onmessage (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\Receiver.js:389:14)    at Receiver.getData (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (C:\Users\Pichau\Downloads\poloniex-trade-bot-master\node_modules\ws\lib\WebSocket.js:138:22)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)

**Comment by lpinca** [comment]
What version of `autobahn` are you using? Run `npm ls autobahn` from the root of your project.
This seems an external issue though as error is thrown by `autobahn` not `ws`.

**Comment by lpinca** [comment]
https://github.com/crossbario/autobahn-js/blob/ac254578644d7e0fcfd38ed8867f94481bd806c5/package/lib/transport/websocket.js#L99 this no longer works with ws@>=3.0.0.

You can either downgrade `ws` or upgrade `autobahn`. There is not much we can do here.
