### ISSUE TITLE
TypeError: Cannot read property 'abort' of null

### ISSUE THREAD

**Issue by neophob** [websockets/ws#1280]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Using ws v4.0.0 is discovered this error:

```
/foo/node_modules/ws/lib/websocket.js:630
      this._req.abort();
               ^

TypeError: Cannot read property 'abort' of null
    at ClientRequest._req.setTimeout (/foo/node_modules/ws/lib/websocket.js:630:16)
    at ClientRequest.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:620:10)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
```

#### Reproducible in:

version: 4.0.0
Node.js version(s): 6.9.x
OS version(s): osx

#### Steps to reproduce:

changed network while app is still running, on the new network the old ssl enabled ws target is not available anymore

**Comment by lpinca** [comment]
Are you using [`'uncaughtException'`](https://nodejs.org/dist/latest/docs/api/process.html#process_event_uncaughtexception)? See https://github.com/websockets/ws/issues/1229#issuecomment-341575553

**Comment by neophob** [comment]
Thanks @lpinca for the fast feedback. No I don't use / catch `uncaughtException`. But I had two different errors before:

```
Error: Opening handshake has timed out at ClientRequest._req.setTimeout (/foo/node_modules/ws/lib/websocket.js:631:21) at ClientRequest.g (events.js:291:16) at emitNone (events.js:86:13) at ClientRequest.emit (events.js:185:7) at TLSSocket.emitTimeout (_http_client.js:620:10) at TLSSocket.g (events.js:291:16) at emitNone (events.js:86:13) at TLSSocket.emit (events.js:185:7) at TLSSocket.Socket._onTimeout (net.js:339:8) at ontimeout 
```

```
Error: connect ENETDOWN 10.0.0.67:1443 - Local (192.168.178.29:56406) at Object.exports._errnoException (util.js:1026:11) at exports._exceptionWithHostPort (util.js:1049:20) at connect (net.js:879:16) at net.js:968:9 at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ENETDOWN', errno: 'ENETDOWN', syscall: 'connect', address: '10.0.0.67', port: 1443 } 
```

**Comment by lpinca** [comment]
Ignore my previous comment, this is different but why isn't the timeout cleared? if `this._req === null`, the request had an [error](https://github.com/websockets/ws/blob/a04d9855a5a3d9bab62f9d22bcf5d1ee8185726b/lib/websocket.js#L638) or it has been [upgraded](https://github.com/websockets/ws/blob/a04d9855a5a3d9bab62f9d22bcf5d1ee8185726b/lib/websocket.js#L658). In both cases there shouldn't be an active timeout.

**Comment by lpinca** [comment]
Can you consistently reproduce this? Did you receive those errors in that order?

1. Opening handshake has timed out
2. connect ENETDOWN
3. Cannot read property 'abort' of null

**Comment by neophob** [comment]
> Can you consistently reproduce this?

Well I'll check if I can - I guess yes. I closed my macbook in the office and opened the lid at home, of course there will be a timeout. I'll recheck if I can reproduce that

**Comment by lpinca** [comment]
Thank you. This is weird as 2 and 3 should never happen if 1 happens. I guess the timeout was put on sleep when you closed your laptop but what happened when you reopened it is crazy as the timeout callback was called twice.
