### ISSUE TITLE
Cannot read property 'aborted' of null 

### ISSUE THREAD

**Issue by ztiandan** [websockets/ws#1305]
How could i catch this error, let node doesn't crash?

node: 9.5.0
ws: 3.3.2
node-tunnel: 0.0.5
```
TypeError: Cannot read property 'aborted' of null (uncaughtException throw 1 times on pid:2253)
    at ClientRequest._req.on (/var/www/html/site_avalokitesvara/node_modules/ws/lib/WebSocket.js:632:19)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._emitTLSError (_tls_wrap.js:603:10)
    at TLSWrap.onerror (_tls_wrap.js:258:11)
```
```
this.wsSock.appLayer = this;
      this.wsSock.onopen = this.onopen;
      this.wsSock.onclose = this.onclose;
      this.wsSock.onerror = this.onerror;
      this.wsSock.onmessage = this.onmessage;
```
disabled
```
    // process.on('uncaughtException', (err) => {
    //   console.error('uncaughtException', err);
    // });
```

**Comment by lpinca** [comment]
Already discussed in https://github.com/websockets/ws/issues/1229 and https://github.com/websockets/ws/pull/1201. Don't use `process.on('uncaughtException')`, add a listener for the `'error'` event on the client instead.
