### ISSUE TITLE
TypeError: Buffer.alloc is not a function

### ISSUE THREAD

**Issue by fengwilliam** [websockets/ws#1318]
#### Description
when i used the 5.0 version to test the ws performance, I found this issue.

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/home/william/node_modules/ws/lib/constants.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/william/node_modules/ws/lib/permessage-deflate.js:7:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

#### Reproducible in:

version:5.0.0
Node.js version(s):v4.2.6
OS version(s):ubuntu 16.04

#### Steps to reproduce:

1.npm install --save ws
2.creat test script
var WebSocketServer = require('ws').Server,
wss = new WebSocketServer({ port: 2345 });
wss.on('connection', function (ws) {
    console.log('client connected');
    ws.on('message', function (message) {
        console.log(message);
    });
});
3. run the test script

**Comment by lpinca** [comment]
> Node.js version(s):v4.2.6

Node.js < 4.5.0 is no longer supported.
