### ISSUE TITLE
I can't get  IP address.

### ISSUE THREAD

**Issue by ryuqing** [websockets/ws#1336]
when i run the example 
`const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws, req) {
  const ip = req.connection.remoteAddress;
});`

it's show that req is not defined
`    const ip = req.connection.remoteAddress;
                  ^
TypeError: Cannot read property 'connection' of undefined
    at WebSocketServer.connection (/data/www/btckan_task/node/websocketServer/server.js:6:19)
    at WebSocketServer.emit (events.js:107:17)
    at /data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:79:14
    at completeHybiUpgrade2 (/data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:262:5)
    at completeHybiUpgrade1 (/data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:287:13)
    at WebSocketServer.handleHybiUpgrade (/data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:315:3)
    at WebSocketServer.handleUpgrade (/data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:152:26)
    at Server.<anonymous> (/data/www/btckan_task/node/node_modules/ws/lib/WebSocketServer.js:77:12)
    at Server.emit (events.js:118:17)
    at Socket.socketOnData (_http_server.js:368:14)`

**Comment by ryuqing** [comment]
it's worked by do this   ` var ip = ws._socket.remoteAddress`

**Comment by lpinca** [comment]
Use `ws@3` or greater.

**Comment by thomaszdxsn** [comment]
@lpinca 

Sorry, what is `ws.upgradeReq`, I can't found it in [API reference](https://github.com/websockets/ws/blob/master/doc/ws.md).

**Comment by lpinca** [comment]
It has been remove in `ws@3`, it's the same `http.IncomingMessage` instance that is now passed as the second argument to the listeners of the `'connection'` event.

**Comment by thomaszdxsn** [comment]
Thanks very much
