### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by DonPrus** [websockets/ws#1371]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
When I refreshing page in Chrome it crashed wss server.
And there is no problems with Firefox.

#### Reproducible in:

version: 5.1.1
Node.js version(s): 8.9.1
npm version: 5.6.0
OS version(s): MacOS Chrome 66.0.3359.117

#### Steps to reproduce:

1. Open a page that connect to websocket server in Chrome
2. Reload page

### Expected result:
Everythins is ok.

### Actual result:
Node js is failing:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
```

I see this issue: https://github.com/websockets/ws/issues/1256, and try to add:
```
ws.on('error', () => {});
```
But it doesn't help me.

I've solve this only if add beforeunload listener.
```
window.addEventListener('beforeunload', function () {
  ws.close();
});
```
But I don't think that it is best practice. So maybe I could fix it in another way?

**Comment by artofspeed** [comment]
@DonPrus Have you solved it? Encountering the same thing.
