### ISSUE TITLE
EHOSTUNREACH throws an exception and terminates the app

### ISSUE THREAD

**Issue by goroka** [websockets/ws#1424]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

In my simple node js based websocket proxy , when connecting to a backend server and having an EHOSTUNREACH tcp error, exception is being thrown (and the app is terminated) instead of emitting an error event

My code snipplet is:
```javascript
const wsCallback =  (ws) => {
    let socket;
    let connected = false;
    let initRRC;
    ws.on('close', () => {
        if (socket) {
            socket.close();
            socket = undefined;
        }
    });
    ws.on('error', () => {
        if (socket) {
            socket.close();
            socket = undefined;
        }
    });

    ws.on('message', (msg) => {
        if (connected) {
            socket.send(msg);
        } else {
            try {
                const connStr = JSON.parse(msg.toString());
                if (connStr.func === 'connect') {
                    initRRC = connStr.rrc;

                    // Some code to determine the backend server to connect to
                    // ...

                    socket = new WebSocket(`ws://${backEndServer}:${backEndPort}`);
                    socket.on('open', () => {
                        connected = true;
                        ws.send(JSON.stringify({ connected: 1, rrc: initRRC }));
                    });
                    socket.on('close', () => {
                        ws.close();
                    });
                    socket.on('error', () => {
                        ws.close();
                    });
                    socket.on('message', (fromBackEnd) => {
                        ws.send(fromBackEnd);
                    });
                }
            } catch (e) {
                ws.close();
            }
        }
    });
};

const proxyServer = new WebSocket.Server({ port: config.args.wsPort, perMessageDeflate: true });
proxyServer.on('connection', wsCallback);
```

#### Reproducible in:

version: 5.2
Node.js version(s): 8.9.4
OS version(s):  4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

#### Steps to reproduce:

1. After several hours of running it happes

### Expected result:

Do not throw an exception, but just emit an error event.

### Actual result:

```javascript
events.js:183
     throw er; // Unhandled ‘error’ event
     ^
Error: connect EHOSTUNREACH ***IP****:**PORT**
   at Object._errnoException (util.js:1022:11)
   at _exceptionWithHostPort (util.js:1044:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

**Comment by lpinca** [comment]
I can't reproduce. In the target host I blocked all incoming traffic sending back an error packet to trigger the `EHOSTUNREACH` error:

```
$ sudo iptables -A INPUT -j REJECT --reject-with icmp-host-unreachable
```
Then from another machine I then tried to connect to the target host

```
$ cat index.js 
'use strict';

const WebSocket = require('ws');

const ws = new WebSocket('ws://192.168.0.31:8080');

ws.on('error', console.error);
```

```
$ node index.js 
{ Error: connect EHOSTUNREACH 192.168.0.31:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.0.31',
  port: 8080 }
```

The error is properly handled by the `'error'` listener and as expected is not thrown.
