### ISSUE TITLE
self signed certificate in certificate chain err 

### ISSUE THREAD

**Issue by MLiranG** [websockets/ws#1433]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

after installing discord.js

> npm i discord.js --save

i'm trying to node my main file and i can't

#### Reproducible in:

version:
Node.js version(s): 8.11.4
OS version(s): 64x bits

#### Steps to reproduce:

1.make a discord bot
2.install discord.js
3.node main file

### Expected result:

the bot will run correctly

### Actual result:

Getting a ws error with a thing they don't have in their npm

### Attachments:

```js
ErrorEvent {
  target:
   WebSocket {
     domain: null,
     _events:
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     _error: null,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: null },
  type: 'error',
  message: 'self signed certificate in certificate chain',
  error: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } }
```

**Comment by lpinca** [comment]
I can't reproduce:

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://gateway.discord.gg/?v=6&encoding=json');

ws.on('open', () => console.log('It works'));
```

If this is an issue in `discord.js` please file an issue in their issue tracker.

**Comment by lpinca** [comment]
It works as expected on my side:

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log('working');
});

client.on('debug', console.log);

client.login('foo');
```

```
$ node index.js 
Authenticated using token foo
Using gateway wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Connecting to wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Identifying as a new session
[ws] [connection] Setting a heartbeat interval for 41250ms
[ws] [connection] Server closed the WebSocket connection: 4004
[ws] [connection] Clearing heartbeat interval
[ws] [connection] Tried to identify with an invalid token
[ws] [connection] Clearing heartbeat interval
[ws] [connection] Attempted to destroy WebSocket but no connection exists!
(node:2021) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (/Users/luigi/Desktop/gh-1433/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:273:13)
    at WebSocketConnection.emit (events.js:182:13)
    at WebSocketConnection.onClose (/Users/luigi/Desktop/gh-1433/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocket.onClose (/Users/luigi/Desktop/gh-1433/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (/Users/luigi/Desktop/gh-1433/node_modules/ws/lib/websocket.js:220:12)
    at Receiver.cleanup (/Users/luigi/Desktop/gh-1433/node_modules/ws/lib/receiver.js:535:15)
    at WebSocket.finalize (/Users/luigi/Desktop/gh-1433/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:187:15)
(node:2021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
