### ISSUE TITLE
Execute error!

### ISSUE THREAD

**Issue by world70104** [websockets/ws#1462]
const WebSocket = require('ws');
const ws = new WebSocket('ws://www.host.com/path');
ws.on('open', function open() {
  ws.send('something');
});
ws.on('message', function incoming(data) {
  console.log(data);
});
---------------
When execute up, show error
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.req.on (/Volumes/Data/WebSocket/JS/websocket/test/node_modules/ws/lib/websocket.js:535:5)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
-----------------------
 if const ws = new WebSocket('ws://www.host.com/path'); change const wss = new WebSocket.Server({ port: 8080 });, there is no error

What reason?

Regards

**Comment by lpinca** [comment]
Check in the closed issues you'll find many answers for this.
