### ISSUE TITLE
add instructions on how to use examples

### ISSUE THREAD

**Issue by cs01** [websockets/ws#1465]
- [x ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Examples do not work and have no documentation. A README file would help here. The folder structure is also inconsistent. There is a file called `ssl.js` next to three folders.

#### Reproducible in:

version: d2317b1d8dda7d36f1ba952f533ff45e2464ae52
Node.js version(s): 8.11.1
OS version(s):

#### Steps to reproduce:

1. cd examples/serverstats
2. npm install
3. node server.js

### Expected result:
server runs

### Actual result:
```
>> node server.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'async-limiter'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cssmith/git/ws/lib/permessage-deflate.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by lpinca** [comment]
This is trivial enough also for beginners to figure out.
After cloning the repo, run `npm install` from the root folder.
Move the examples folder, the `ssl` example has no external deps, it can run as is. All other examples have additional deps.
Move to their folder, run `npm install`, run the example.

This is a common patter used in multiple projects. For example `https://github.com/expressjs/express` does the same.

I don't think it deserves special documentation.
