### ISSUE TITLE
TypeError: URL is not a constructor on node v6.12.0

### ISSUE THREAD

**Issue by Apollon77** [websockets/ws#1472]
I use your library in a project and now one user complains about an error with URL is not a contructor.

Library version is 6.1.1
nodejs is v6.12.0

Could it be that 

https://github.com/websockets/ws/commit/0da3fdb506dd8a8a3ae2837873cd9878fe1f6965

broke nodejs 6.x compatibility somehow or what could be the reason?

Code place where it is used is https://github.com/Apollon77/alexa-remote/blob/master/alexa-wsmqtt.js#L37

Exception:

```
2018-11-17 13:57:26.129  - [31merror[39m: alexa2.0 uncaught exception: URL is not a constructor
2018-11-17 13:57:26.131  - [31merror[39m: alexa2.0 TypeError: URL is not a constructor
    at WebSocket.initAsClient (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:450:17)
    at new WebSocket (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:62:20)
    at AlexaWsMqtt.connect (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-wsmqtt.js:37:26)
    at AlexaRemote.initWsMqttConnection (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:543:26)
    at prepare (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:118:30)
    at getNotifications (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:170:25)
    at IncomingMessage.res.on.e (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:653:58)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/master/.travis.yml#L7

Can you update you Node.js version?

**Comment by lpinca** [comment]
I recommend to update to the latest v6.x as there are at least 2 security releases since v6.12.0.

**Comment by Apollon77** [comment]
I can tell this to the user, BUT: This will not solve this issue!!!

**Comment by Apollon77** [comment]
PS: in general: if the dep is really >=6.13.0 then you should reflect that in the package.json ... or ?! Else it installs successfully and updates the version also for users with a lower version ... like happened here :-(

**Comment by lpinca** [comment]
What we can do is revert https://github.com/websockets/ws/commit/0da3fdb506dd8a8a3ae2837873cd9878fe1f6965 and cut a new minor version. I'd prefer to not do it though.

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by lpinca** [comment]
Done, ws@6.1.2 is out.

**Comment by Apollon77** [comment]
Great, thank you very much!
