### ISSUE TITLE
maxPayload option in Websocket Client is not working properly

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1526]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am creating a websocket client to connect to a server.

 const ws = new WebSocket('wss://localhost:8989/', {
        cert: fs.readFileSync(path.normalize(serverCertPath)),
        key: fs.readFileSync(path.normalize(serverKeyPath)),
        rejectUnauthorized: false,
        maxPayload: frameSize
      });

I am setting the maxPayload option to limit the maximum message I can send in one go.

Right now I am setting it to 2048 bytes (2KB).

And I am chunking the input data  buffer into chunks and each chunk is of length 180 bytes or so and I am sending it over websockets,

   for (let i = 0; i < fragmentsLength - 1; i++) {
            // tslint:disable-next-line:no-console
            console.log('Fragment Size: ' + fragments[i].length);
            ws.send(fragments[i], {binary: true, fin: false});
          }
  ws.send(fragments[fragmentsLength - 1], {binary: true, fin: true});

When I do the above operation, websocket is giving me exceptions,

 RangeError: Max payload size exceeded
    at Receiver.haveLength (C:\RefPlatform\core\reference_platform\node_modules\ws\lib\receiver.js:287:16)
    at Receiver.getPayloadLength64 (C:\RefPlatform\core\reference_platform\node_modules\ws\lib\receiver.js:273:17)
    at Receiver.startLoop (C:\RefPlatform\core\reference_platform\node_modules\ws\lib\receiver.js:127:22)
    at Receiver._write (C:\RefPlatform\core\reference_platform\node_modules\ws\lib\receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (C:\RefPlatform\core\reference_platform\node_modules\ws\lib\websocket.js:816:35)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12) [Symbol(status-code)]: 1009 }
Exception: RangeError: Max payload size exceeded

#### Reproducible in:

- version: Latest
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
The option is for the data that is received, not sent. There is no limit on send.

**Comment by lpinca** [comment]
Also it is applied to sum of all fragments length (the whole message).

**Comment by shaiksyedali** [comment]
Ohh Okay.

On the same lines, is there any option by which we can limit the amount of data we send over websockets from client?

**Comment by lpinca** [comment]
There is not as you can control that. For example, set a limit, every time you call `ws.send()` increment a counter. If the counter value exceeds limit, stop sending.
