### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established error while creating a secure websocket connection

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1529]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am trying to create a secure websocket client and server.

Server code:

```
var options = { 
	key: clientKey, 
	cert: clientCert, 
	ca: caCert,
	passphrase: 'test',
	requestCert: true
}; 

var httpsServer = https.createServer(options);

var WebSocketServer = WebSocket.Server;
var wss = new WebSocketServer({
		verifyClient: (info) => {
		  	console.log('Request from client :'+ info.req.rawHeaders);
		  	console.log('Request from client auth :'+ info.req.client.authorized);
          	success = !!info.req.client.authorized;
          	return success;
		},
		server: httpsServer
});
```

Client Code:

```
const ws = new WebSocket('wss://localhost:8989/',
          'com.hp.cdm.service.ioFilter.version.1.type.filterStream', {
            cert: fs.readFileSync(path.normalize(serverCertPath)),
            key: fs.readFileSync(path.normalize(serverKeyPath)),
            ca: fs.readFileSync(path.normalize(caCert)),
            passphrase: 'test',
            rejectUnauthorized: false,
          });
```

When I try to make a connection from client to server, I am getting the following error,

{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: undefined,
  host: 'localhost',
  port: '8989',
  localAddress: undefined }

What am I doing error? Any TLS version mismatch? Or some certificate error?

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
On your server add a `'request'` handler

```js
httpsServer.on('request', function(res) {
  res.end('OK');
});
```

Then use https://nodejs.org/api/https.html#https_https_get_url_options_callback to debug. When it works use the same options on ws.

**Comment by shaiksyedali** [comment]
I tried this. Same error.

Client:

```
 const options = {
      hostname: 'localhost',
      port: 8989,
      path: '/',
      method: 'GET',
      key: fs.readFileSync(path.normalize(serverKeyPath)),
      cert: fs.readFileSync(path.normalize(serverCertPath)),
      ca: fs.readFileSync(path.normalize(caCertPath)),
      passphrase: 'test',
    };

    const https = require('https');

    const req = https.request(options, (res: any) => {
      res.on('data', (data: any) => {
        // tslint:disable-next-line:no-console
        console.log(data);
      });
    });

    req.end();

    req.on('error', (e: any) => {
      // tslint:disable-next-line:no-console
      console.error(e);
    });
```

Server:

```
var options = { 
	key: clientKey, 
	cert: clientCert, 
	ca: caCert,
	passphrase: 'test',
	requestCert: true
}; 


var httpsServer = https.createServer(options, function (req, res) { 
	console.log('Received request');
    res.writeHead(200); 
    res.end("hello world\n"); 
});

```

Now when I make a GET request from the client to the server, I am getting the same error. The request is not going to the server.

```
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: null,
  host: 'localhost',
  port: 8989,
  localAddress: undefined }
```

**Comment by lpinca** [comment]
Yes, it does not seem to be a ws issue. You have to figure out by yourself, sorry.
