### ISSUE TITLE
After handleUpgrade server crashes

### ISSUE THREAD

**Issue by bartosz-m** [websockets/ws#1531]
#### Description
When trying to manually upgrade connection using code:
```js
server.on('upgrade', function(request, socket, head){
  wss.handleUpgrade(request, socket, head, function(websocket){
    console.log("new websocket");
  });
});
```
server crashes with error

#### Reproducible in:

- version: 6.2.0
- Node.js version(s): v10 and v11
- OS version(s): Linux

#### Steps to reproduce:

1. Run server
```js
const http = require('http');
const ws = require('ws');

var port;
port = 3311;
var server = http.createServer();
var wss = new ws.Server({
  server: server,
  noServer: true
});

server.on('upgrade', function(request, socket, head){
  wss.handleUpgrade(request, socket, head, function(websocket){
    console.log("new websocket");
  });
});

server.listen(port);

```

2.
run client with script
```js
var socket = new WebSocket('ws://localhost:3311')
```

#### Expected result:

No crash connection established

#### Actual result:

server crashes with this error when firefox clients connects:
```
 websocket.readyState = WebSocket.CLOSING;
                       ^

TypeError: Cannot set property 'readyState' of undefined
    at Socket.socketOnClose (/home/bartek/Projekty/ehelon/discovery/node_modules/ws/lib/websocket.js:829:24)
    at Socket.emit (events.js:202:15)
    at TCP._handle.close (net.js:611:12)
```

and with this when chrome is connecting
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Receiver.Writable.write (_stream_writable.js:296:5)
    at Socket.socketOnData (/home/bartek/Projekty/ehelon/discovery/node_modules/ws/lib/websocket.js:867:35)
    at Socket.emit (events.js:202:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
Emitted 'error' event at:
    at Receiver.receiverOnError (/home/bartek/Projekty/ehelon/discovery/node_modules/ws/lib/websocket.js:772:13)
    at Receiver.emit (events.js:197:13)
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at writeAfterEnd (_stream_writable.js:250:3)
    at Receiver.Writable.write (_stream_writable.js:296:5)
    [... lines matching original stack trace ...]
    at Socket.Readable.push (_stream_readable.js:224:10)
```

**Comment by lpinca** [comment]
```js
var wss = new ws.Server({
  server: server,
  noServer: true
});
```

This is wrong. Use only `noServer`.

**Comment by bartosz-m** [comment]
Thank it worked! :smiley:

**Comment by screets** [comment]
> ```js
> ```js
> var wss = new ws.Server({
>   server: server,
>   noServer: true
> });
> ```
> 
> 
> This is wrong. Use only noServer.
> ```

Love you. Do you think it is secure for production servers. I use nginx for websockets.

**Comment by travis5491811** [comment]
> > ```js
> > ```js
> > var wss = new ws.Server({
> >   server: server,
> >   noServer: true
> > });
> > ```
> > 
> > 
> > This is wrong. Use only noServer.
> 
> Love you. Do you think it is secure for production servers?
> I use nginx for websockets.

You need to add auth. Example https://github.com/websockets/ws#client-authentication

**Comment by screets** [comment]
Hey Websockets/ws,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *s**creets API key* which is
required for support questions.
If you already included in your message, you don't need to do anything else.

Best,
screets
{#HS:1549781585-9545#}
