### ISSUE TITLE
naming of variable `server` cause exception TypeError

### ISSUE THREAD

**Issue by wenxinleong** [websockets/ws#1557]
**Version**
express: v4.16.4
ws: v7.0.0
node.js: v8.10.0
OS: Ubuntu 18.04.1 LTS

**Description** 
By changing the name of variable `const server = http.createServer(app);` to anything other than `server` will cause following error:

```
      throw new TypeError(
      ^

TypeError: One of the "port", "server", or "noServer" options must be specified
    at new WebSocketServer (/home/ubuntu/03_trackerslove/websocket-delme/ws/examples/express-session-parse/node_modules/ws/lib/websocket-server.js:59:13)
    at Object.<anonymous> (/home/ubuntu/03_trackerslove/websocket-delme/ws/examples/express-session-parse/index.js:7:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Reproduce Error**
To reproduce, simply rename `server` to `serverr`:

```
const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const app = express();
const serverr = http.createServer(app);

const wss = new WebSocket.Server({
  serverr
});

wss.on('connection', function(ws, request) {
  ws.on('message', function(message) {
  });
});

serverr.listen(80, function() {
  console.log('Listening on http://localhost:8080');
});
```

**Comment by majneeds2chill** [comment]
So is this the intended behavior then?
