### ISSUE TITLE
How can i use ws with HttpsProxyAgent

### ISSUE THREAD

**Issue by syter** [websockets/ws#1601]
My project is create a websocket connection between my computer and a internet websocket server.
Now I want to use proxy.
I get some proxy IP from Internet. Such as: 'http://51.38.71.101:8080'.

Here is my code:
```
var WebSocket = require('ws');
var http = require("http");
var HttpProxyAgent = require('http-proxy-agent');
var HttpsProxyAgent = require('https-proxy-agent');
var urlUtil = require('url');

var reconnectInterval = 30 * 1000;
var reconnectTimeCount = 0;
var reconnectTotalCount = 10000;
var socket;
var proxy = 'http://51.38.71.101:8080';
var options = urlUtil.parse(proxy);
// var agent = new HttpsProxyAgent(options);
var agent = new HttpProxyAgent(options);

var connect = function(){
    try {
        console.log("========000000======");
        var url = 'ws://115.231.140.70';
        // socket = new WebSocket(url, { agent: agent });
        socket = new WebSocket(url);
        console.log("========1111======");
        socket.on('open', function() {
            console.log("=====connect====success====");
        });
        socket.on('message', function (data, flags) {
            console.log("=====received msg====");
        });
        socket.on('error', function(err) {
            console.log("************" + 'socket error'+ require('util').inspect(err));
        });
        socket.on('close', function() {
            console.log('socket close' + "===============reconnectTimeCount="+reconnectTimeCount);
            if (reconnectTimeCount <= reconnectTotalCount) {
                setTimeout(connect, reconnectInterval);
                reconnectTimeCount ++;
            }
        });
        console.log("========222222======");
    } catch (e) {
        console.log("========333333======");
    }   
    
};

connect();
```

When I use `socket = new WebSocket(url);`, my console log is:
```
SyterLius-MacBook-Air:app Syter$ node test.js 
========000000======
========1111======
========222222======
=====connect====success====
```

But when I use `socket = new WebSocket(url, { agent: agent });`, my console log is: 
```
SyterLius-MacBook-Air:app Syter$ node test.js 
========000000======
========1111======
========222222======
************socket errorError: Unexpected server response: 101
    at ClientRequest.req.on (/Users/Syter/Documents/workcode/moshan/hyserver/node_modules/ws/lib/websocket.js:579:7)
    at ClientRequest.emit (events.js:188:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at Socket.socketOnData (_http_client.js:449:20)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:145:17)
socket close===============reconnectTimeCount=0
```

I have test proxy IP in `http.get` way like documents said, it's no problem
So how can I do for it??

And my node version is `v11.7.0`
ws version is `7.0.1`
https-proxy-agent version is `2.2.1`
http-proxy-agent version is `2.1.0`

**Comment by lpinca** [comment]
Here is an example https://github.com/websockets/ws/issues/1276#issuecomment-357355842. The proxy server should accept CONNECT requests.

Anyway it seems the module need to be fixed to work with Node.js >= 10, see https://github.com/TooTallNate/node-https-proxy-agent/pull/58

**Comment by syter** [comment]
I will test again with node.js < 10, if ok or not, I will back.

**Comment by syter** [comment]
I have test it in node.js 9.0.0, and result is the same.
Here is my logs:

```
SyterLius-MacBook-Air:app Syter$ /Applications/node-v9.0.0-darwin-x64/bin/node -v
v9.0.0
SyterLius-MacBook-Air:app Syter$ /Applications/node-v9.0.0-darwin-x64/bin/node test.js 
========000000======
========1111======
========222222======
************socket errorError: Unexpected server response: 101
    at ClientRequest.req.on (/Users/Syter/Documents/workcode/moshan/hyserver/node_modules/ws/lib/websocket.js:579:7)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
socket close===============reconnectTimeCount=0
^C
SyterLius-MacBook-Air:app Syter$ 
SyterLius-MacBook-Air:app Syter$ 
SyterLius-MacBook-Air:app Syter$ telnet 41.65.147.36 8080
^C
SyterLius-MacBook-Air:app Syter$ 
SyterLius-MacBook-Air:app Syter$ 
SyterLius-MacBook-Air:app Syter$ curl -x http://41.65.147.36:8080 http://www.baidu.com
<!DOCTYPE html>
<!--STATUS OK--><html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn"></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=http://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');</script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>

```

It seems the proxy IP cannot accept CONNECT requests, cause I cannot telnet it. right?

**Comment by syter** [comment]
I get about 300 proxy IP from internet. 
I write a batch create ws connection code to handle them, and I found some of them failed like the test.js output, some of them print connection successful.
So some proxy IP is bad, i think.

**Comment by lpinca** [comment]
Yes, free proxies available online are not reliable. Test it with your own proxy.
Closing as answered. Discussion can continue if needed.
