### ISSUE TITLE
websocket crash during the ping with error ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by Jonas121** [websockets/ws#1642]
- [yes ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version:
- Node.js version(s): 11.16.0 and higher
- OS version(s): Linux

#### Steps to reproduce:

1. Using websocket server on node 11.15.0 and decided to migrate node to latest version. During the tests used node 12.11.0.

2. Client connects to server and starts consuming services. During the ~20 seconds web server crash with uncaught error despite I am processing error event on my websocket server:

wss.on('connection', function connection(ws, req) {
	ws.isAlive = true;
	ws.on('pong', heartbeat);
	ws.on('message', function incoming(message) {
	});
	ws.on('error', function (err) {
		logger.error("WS error", err)
	}); 
});

#### Expected result:

websocket server event error should catch errors in websocket connections.

#### Attachments:

buffer.js:293
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type function
    at Function.from (buffer.js:293:9)
    at Sender.ping (/home/ec2-user/node_modules/ws/lib/Sender.js:178:23)
    at WebSocket.ping (/home/ec2-user/node_modules/ws/lib/WebSocket.js:318:18)
    at each (/home/ec2-user/release/wsserver1.js:168:8)
    at Set.forEach (<anonymous>)
    at Timeout.ping [as _onTimeout] (/home/ec2-user/release/wsserver1.js:165:15)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by Jonas121** [comment]
Ammendment:

I succeed to catch error. It actually happen in my websocket server ping code here:

function noop() {}
 
function heartbeat() {
  this.isAlive = true;
} 

const interval = setInterval(function ping() {
	try {
  wss.clients.forEach(function each(ws) {
    if (ws.isAlive === false) return ws.terminate();
    ws.isAlive = false;
    ws.ping(noop);
  });
	} catch (err) {
		logger.log(err)  <-- now my error here
	}
}, 30000);


Comment - I am using same ping code for node 11.15.0 and 12.11.0 versions. For 11.15.0 working smooth. Ping code is from official ws documentation.

**Comment by Jonas121** [comment]
shows 3.3.3. Seems there are internal issues on my side, why it's catching old ws version.
