### ISSUE TITLE
Error: self signed certificate trying to connect to vis WSS using vscode extension

### ISSUE THREAD

**Issue by Wathsara** [websockets/ws#1650]
I am trying to connect to the wss.
```

var WebSocket = require('ws');
var webSocket = new WebSocket('wss://localhost:8443/cart'); 
```

It connect without an error with the normal javascript. but when I am trying to connect to this with vscode extension it gives an error like
```

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
Emitted 'error' event at:
    at ClientRequest.req.on (/home/project/node_modules/ws/lib/websocket.js:554:15)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
#### Steps to reproduce:
```

**Comment by lpinca** [comment]
Use the `rejectUnauthorized` option:

```js
const ws = new WebSocket('wss://localhost:8443/cart', { rejectUnauthorized: false });
```
