### ISSUE TITLE
npm i -g prisma crashes - error in dependency on ws?

### ISSUE THREAD

**Issue by johnalupton** [websockets/ws#1694]
#### Description

```
npm i -g prisma and install crashes with error 
npm ERR! Unexpected end of JSON input while parsing near '...w5I59BEWCiR+DAqYw\nmO'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ ... \npm-cache\_logs\2020-02-15T07_22_53_690Z-debug.log

```
#### Reproducible in:

- version: @latest
- Node.js version(s) v12.13.0:
- OS version(s):

verbose Windows_NT 10.0.18362
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "prisma"
verbose node v12.13.0
verbose npm  v6.12.0

#### Steps to reproduce:

1. `npm i -g prisma`

2.

3.

#### Expected result:

prisma installed
#### Actual result:
from debug log:
```
...

119 silly resolveWithNewModule scuid@1.1.0 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/prisma-generate-schema 127ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/prisma-client-lib 155ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/sillyname 107ms (from cache)
123 silly pacote version manifest for prisma-generate-schema@1.34.10 fetched in 151ms
124 silly resolveWithNewModule prisma-generate-schema@1.34.10 checking installable status
125 silly pacote version manifest for prisma-client-lib@1.34.10 fetched in 174ms
126 silly resolveWithNewModule prisma-client-lib@1.34.10 checking installable status
127 silly pacote range manifest for sillyname@^0.1.0 fetched in 111ms
128 silly resolveWithNewModule sillyname@0.1.0 checking installable status
129 http fetch GET 304 https://registry.npmjs.org/table 103ms (from cache)
130 silly pacote range manifest for table@^4.0.1 fetched in 106ms
131 silly resolveWithNewModule table@4.0.3 checking installable status
132 http fetch GET 304 https://registry.npmjs.org/prisma-yml 157ms (from cache)
133 silly pacote version manifest for prisma-yml@1.34.10 fetched in 169ms
134 silly resolveWithNewModule prisma-yml@1.34.10 checking installable status
135 http fetch GET 304 https://registry.npmjs.org/multimatch 697ms (from cache)
136 silly pacote range manifest for multimatch@^2.1.0 fetched in 702ms
137 silly resolveWithNewModule multimatch@2.1.0 checking installable status
138 timing stage:rollbackFailedOptional Completed in 1ms
139 timing stage:runTopLevelLifecycles Completed in 1458ms
140 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...w5I59BEWCiR+DAqYw\nmO'
140 verbose stack     at JSON.parse (<anonymous>)
140 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
140 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
140 verbose stack     at runMicrotasks (<anonymous>)
140 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
141 verbose cwd C:\Users\ .... [REDACTED USER INFO]
142 verbose Windows_NT 10.0.18362
143 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "prisma"
144 verbose node v12.13.0
145 verbose npm  v6.12.0
146 error Unexpected end of JSON input while parsing near '...w5I59BEWCiR+DAqYw\nmO'
147 verbose exit [ 1, true ]
```

**Comment by lpinca** [comment]
I see no track of ws in the log.
