### ISSUE TITLE
How to handle this error?

### ISSUE THREAD

**Issue by alza54** [websockets/ws#1719]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

```js
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 502
    at ClientRequest.<anonymous> (/code/node_modules/ws/lib/websocket.js:580:7)
    at ClientRequest.emit (events.js:223:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at Socket.socketOnData (_http_client.js:456:22)
    at Socket.emit (events.js:223:5)
    at Socket.Readable.read (_stream_readable.js:526:10)
    at Socket.read (net.js:614:39)
    at flow (_stream_readable.js:1001:34)
    at resume_ (_stream_readable.js:982:3)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (/code/node_modules/ws/lib/websocket.js:698:15)
    at ClientRequest.<anonymous> (/code/node_modules/ws/lib/websocket.js:580:7)
    [... lines matching original stack trace ...]
    at flow (_stream_readable.js:1001:34)
error Command failed with exit code 1.`

**Comment by lpinca** [comment]
Add a listener for the `'error'` event on the `WebSocket` instance.

```js
const ws = new WebSocket(url);

ws.on('error', console.error);
```
