### ISSUE TITLE
RangeError: Invalid WebSocket frame: MASK must be set

### ISSUE THREAD

**Issue by andrew-medvedev** [websockets/ws#1721]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

```javascript
RangeError: Invalid WebSocket frame: MASK must be set
    at Receiver.getInfo (/root/.nvm/versions/node/v12.16.1/lib/node_modules/easy-wormhole/node_modules/ws/lib/receiver.js:234:16)
    at Receiver.startLoop (/root/.nvm/versions/node/v12.16.1/lib/node_modules/easy-wormhole/node_modules/ws/lib/receiver.js:130:22)
    at Receiver._write (/root/.nvm/versions/node/v12.16.1/lib/node_modules/easy-wormhole/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Receiver.Writable.write (_stream_writable.js:316:11)
    at Socket.socketOnData (/root/.nvm/versions/node/v12.16.1/lib/node_modules/easy-wormhole/node_modules/ws/lib/websocket.js:876:35)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11) {
  [Symbol(status-code)]: 1002
}
```
That what I've got using ws@7.2.3 with my module: `easy-wormhole`: https://www.npmjs.com/package/easy-wormhole

#### Reproducible in:

- version:
- Node.js version(s): v12.16.1
- OS version(s): Ubuntu Xenial

#### Steps to reproduce:

1. Run 2 node apps to communicate with each other via `ws`

2. Or download my module: https://github.com/andrew-medvedev/easy-wormhole

3. Replace `ws`'s version with latest & run `npm i`

4. Try to send files

#### Expected result:

No error

#### Actual result:

Error

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/releases/tag/7.2.2

The error linked here is raised when a client sends a non masked frame so make sure your WebSocket client sends masked frames.

**Comment by lpinca** [comment]
```
$ cat server.js 
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 }, function () {
  const { address, family, port } = wss.address();
  console.log(
    'Server listening on %s:%d',
    family === 'IPv6' ? `[${address}]` : address,
    port
  );
});
```

```
$ cat client.js 
'use strict';

const WebSocket = require('ws');

const ws = new WebSocket('ws://localhost:8080');
const duplex = WebSocket.createWebSocketStream(ws);

process.stdin.pipe(duplex);
```

```
$ dd if=/dev/urandom of=tmp bs=1m count=1024
1024+0 records in
1024+0 records out
1073741824 bytes transferred in 1.344091 secs (798860853 bytes/sec)
```

Server process

```
$ node server.js 
Server listening on [::]:8080
```

Client process

```
$ cat tmp | node client.js
```

Everything works as expected.
