### ISSUE TITLE
After a few connections, fail with "Error: socket hang up"

### ISSUE THREAD

**Issue by sebpiq** [websockets/ws#173]
I have a simple server which just accept connections, and put connected sockets in an array. Then, on close, I do some cleaning and remove the closed socket from the array.
When I make many connections to the server, then kill the client script, everything seems to work fine `close` is fired, and sockets are cleaned.

However after a certain amount of connections (> 1000), new connections fail with : 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1425:15)
    at Socket.socketOnEnd [as onend] (http.js:1521:23)
    at Socket.g (events.js:175:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:872:14
    at process._tickCallback (node.js:415:13)
```

This can be reproduced with the scripts `server-test.js` and `client-test.js` (see at the bottom) with the following sequence of commands in two terminals : 

**Terminal 1** (and output)

```
> node server-test.js
ws sequencer server listening
New connection, total : 1
...
New connection, total : 1000
Socket disconnected, left : 1000
...
Socket disconnected, left : 0
New connection, total : 1
...
New connection, total : 10
```

**Terminal 2** (and output)

```
> node client-test.js 1000
* connected with server
... 1000 times
* connected with server

> ctrl-c

> node client-test.js 20
* connected with server
... 10 times
* connected with server

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1425:15)
    at Socket.socketOnEnd [as onend] (http.js:1521:23)
    at Socket.g (events.js:175:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:872:14
    at process._tickCallback (node.js:415:13)
```

Then every new connection fail (even only one connection).

I am assuming I just do something wrong ... or something tricky that I don't know about, but just in case I post it here.
## The scripts

Server (`server-test.js`) : 

``` javascript
var _ = require('underscore')
  , WebSocketServer = require('ws').Server
  , server, sockets = []

server = new WebSocketServer({port: 3000, path: '/ws-test'})
server.on('listening', function() {
  console.info('ws server listening')
})

// On connection just add the new socket to the list
server.on('connection', function(socket) {
  sockets.push(socket)
  console.log('New connection, total : ' + sockets.length)

  socket.on('close', function() {
    forgetSocket(socket)
    console.log('Socket disconnected, left : ' + sockets.length)
  })

  socket.on('error', function() {
    console.log('error closing socket ...')
    forgetSocket(socket)
  })
})

// Close the socket properly and remove it from the list
var forgetSocket = function(socket) {
  socket.on('error', function() {
    console.log('error closing socket, terminating ...')
    socket.terminate()
  })
  socket.close()
  socket.removeAllListeners()
  sockets = _.reject(sockets, function(other) {
    return socket === other
  })
}
```

Client (`client-test.js`) : 

``` javascript
var WebSocket = require('ws')
  , _ = require('underscore')
  , connectCount = parseInt(process.argv[2], 10) || 100
  , socket, sockets = []

_.range(connectCount).forEach(function(i) {
  var ws = new WebSocket('ws://localhost:3000/ws-test')
  ws.onopen = function(event) {
    console.log('* connected with server')
  }
  sockets.push(socket)
})
```

**Comment by s1riedel** [comment]
Did anyone ever find a solution to this problem? I am having the same exact problem. The only workaround I have right now is to restart my servers several times a day, which eliminates the problem, but is not a great solution. I would expect ulimit to only apply to sockets that are currently open, but even with only a few hundred sockets open at a time, I start getting socket hang ups on the client after running for several hours.

Thank you.

**Comment by lpinca** [comment]
@s1riedel do you have a test case to reproduce the issue?

**Comment by lpinca** [comment]
Closing due to inactivity, please reopen if needed.

**Comment by chishi2612** [comment]
> Did anyone ever find a solution to this problem? I am having the same exact problem. The only workaround I have right now is to restart my servers several times a day, which eliminates the problem, but is not a great solution. I would expect ulimit to only apply to sockets that are currently open, but even with only a few hundred sockets open at a time, I start getting socket hang ups on the client after running for several hours.
> 
> Thank you.

Hi @s1riedel 
I had the same problem. When i start my websocket after running for several hours, I got socket hang up on client. Do you fix this issue? could you share me the solution? thanks alot
