### ISSUE TITLE
Cannot set property 'readyState' of undefined

### ISSUE THREAD

**Issue by Dominic12** [websockets/ws#1737]
- [X ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version: 7.1.2
- Node.js version(s):10.18.1
- OS version(s): Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

#### Steps to reproduce:

1. Connect to Websocket

2. Refresh

#### Expected result:

No crash

#### Actual result:

Thw whole process crashed.

#### Attachments:

TypeError: Cannot set property 'readyState' of undefined
    at Socket.socketOnClose (/Users/Documents/dev-backend/node_modules/ws/lib/websocket.js:838:24)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at TCP._handle.close (net.js:607:12) {"error":{},"stack":"TypeError: Cannot set property 'readyState' of undefined\n    at Socket.socketOnClose (/Users/Documents/dev-backend/node_modules/ws/lib/websocket.js:838:24)\n    at Socket.emit (events.js:203:15)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at TCP._handle.close (net.js:607:12)","exception":true,"date":"Tue Apr 14 2020 16:36:31 GMT+0200 (Central European Summer Time)","process":{"pid":18351,"uid":501,"gid":20,"cwd":"/Users/dominicjarmann/Documents/dev-backend","execPath":"/usr/local/Cellar/node@10/10.18.1/bin/node","version":"v10.18.1","argv":["/usr/local/Cellar/node@10/10.18.1/bin/node","/Users/dominicjarmann/Documents/dev-backend/src/app.ts"],"memoryUsage":{"rss":150470656,"heapTotal":73293824,"heapUsed":65529288,"external":319772}},"os":{"loadavg":[2.2626953125,2.5400390625,2.47509765625],"uptime":30616},"trace":[{"column":24,"file":"/Users/dominicjarmann/Documents/dev-backend/node_modules/ws/lib/websocket.js","function":"Socket.socketOnClose","line":838,"method":"socketOnClose","native":false},{"column":15,"file":"events.js","function":"Socket.emit","line":203,"method":"emit","native":false},{"column":20,"file":"domain.js","function":"Socket.EventEmitter.emit","line":448,"method":"emit","native":false},{"column":12,"file":"net.js","function":"TCP._handle.close","line":607,"method":"close","native":false}]}

DISCLAIMER: I am using this library via Socket.Io, therefore i created an issue [there.](https://github.com/socketio/engine.io/issues/600#issuecomment-613481971)

As far as i see, onSocketClose is called twice, causing it to fail. But even when implemented an "dirty" check, to make sure that the function returns if websocket is undefined i get a "failed: Invalid frame header" back.

**Comment by lpinca** [comment]
This is most likely caused by an invalid usage of ws. See https://github.com/websockets/ws/issues/1704

**Comment by Dominic12** [comment]
Hi @lpinca, thanks for your response. What could cause this? I checked the other issue again and i don't think that I have the same cause of the issue. How would i see if there were two socket instances? What else could possibly cause this behaviour?

**Comment by lpinca** [comment]
I've answered in the engine.io issue. Let's continue discussion there.
