### ISSUE TITLE
Ws throwing an error upon receiving a ping event

### ISSUE THREAD

**Issue by frosty00** [websockets/ws#1792]
Here is the traceback of the error

```
Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.pong (node_modules\ws\lib\websocket.js:288:13)
    at Receiver.receiverOnPing (node_modules\ws\lib\websocket.js:809:13)
    at Receiver.controlMessage (node_modules\ws\lib\receiver.js:477:12)
    at Receiver.getData (node_modules\ws\lib\receiver.js:350:42)
    at Receiver.startLoop (node_modules\ws\lib\receiver.js:143:22)
    at \node_modules\ws\lib\receiver.js:397:12
    at \node_modules\ws\lib\permessage-deflate.js:306:9
    at \node_modules\ws\lib\permessage-deflate.js:385:7
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8)
```

**Comment by lpinca** [comment]
That's expected, you have to wait for the `'open'` event before calling `websocket.ping()`.

**Comment by lpinca** [comment]
Reopening because the stack trace is a bit weird, the ready state can't be `0` if are receiving ping. Is there a way to reproduce this?

**Comment by lpinca** [comment]
Another weird thing is that you get a compressed frame and this is handled as a control message (ping), but this should not be possible as control messages cannot be compressed.

**Comment by frosty00** [comment]
It happens on a subscription to the https://binance.com trading websocket api.   

> Reopening because the stack trace is a bit weird, the ready state can't be 0 if you are receiving a ping. Is there a way to reproduce this?

We were modifying the readyState but have since changed the code so it doesn't modify this. I will close this issue until we can reproduce it in the new codebase.

**Comment by lpinca** [comment]
Ok, do not change `ws` internals unless you know exactly what you are doing.
