### ISSUE TITLE
connect to wss ignoring certificate (like curl -k)

### ISSUE THREAD

**Issue by mmm286** [websockets/ws#1796]
Hi!
how could I connect to wss without certificate like makes curl -k ?

It gives me a error if connect to wss:

`Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)
`

**Comment by lpinca** [comment]
Use the `rejectUnauthorized` option. Please do not open issues for general support questions.
