### ISSUE TITLE
DeprecationWarning when connection to IP address over wss

### ISSUE THREAD

**Issue by Hornwitser** [websockets/ws#1829]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Connecting to IP addresses over wss causes a deprecation warning to emitted.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 14.9.0
- OS version(s): Linux 5.8.5-arch1-1

#### Steps to reproduce:

Connect to a WebSocket endpoint over a wss url to an IP address:
```js
const WebSocket = require("ws");
const ws = new WebSocket("wss://1.1.1.1/");
ws.on("error", () => {});
```
Observer node print a Deprecation warning:
```
(node:2399511) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
    at Object.connect (_tls_wrap.js:1619:15)
    at Object.tlsConnect [as createConnection] (node_modules/ws/lib/websocket.js:673:14)
    at new ClientRequest (_http_client.js:312:33)
    at request (https.js:312:10)
    at get (https.js:316:15)
    at initAsClient (node_modules/ws/lib/websocket.js:538:31)
    at new WebSocket (node_modules/ws/lib/websocket.js:72:7)
    at Object.<anonymous> (bug.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
```

#### Expected result:

No deprecation warning from using wss urls to IP addresses.

#### Actual result:

ws erroneously set the servername TLS option to an IP address. Compare [what ws does](https://github.com/websockets/ws/blob/c171962844e1862cadff27804700e00e2f2adbf5/lib/websocket.js#L698) vs what [node does](https://github.com/nodejs/node/blob/c27efd4e6bf7ff569a8ee3636eac6efc93a79c3a/lib/_http_agent.js#L304). Node does not set the servername option if the host is an IP address while ws does.

**Comment by lpinca** [comment]
Thank you for the good report.
