### ISSUE TITLE
Webpack issues

### ISSUE THREAD

**Issue by JonNeat** [websockets/ws#1866]
Hi everyone,

I've tried to run my WS client through a webpack (latest) and then trying to run the .js-fil with Node (latest). I got this error:

Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new o.exports (/XXX/wsclient/dist/main.js:1:61)
    at /XXX/dist/main.js:1:442
    at /XXX/wsclient/dist/main.js:1:691
    at Object.<anonymous> (/XXX/wsclient/dist/main.js:1:695)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

Have anyone tried webpacking a client?

**Comment by lpinca** [comment]
See https://github.com/heineiuo/isomorphic-ws.

**Comment by lpinca** [comment]
If you are bundling for Node.js you can use the `node` [target](https://webpack.js.org/configuration/target/) without using `isomorphic-ws`.

**Comment by JonNeat** [comment]
Thanks @lpinca it worked with target: "node".
