### ISSUE TITLE
Any known issues with ws on Azure?

### ISSUE THREAD

**Issue by kimrunar** [websockets/ws#1905]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I have an API hosted on Azure on a node-runtime linux-machine. I wanted to add a socket-connection using ws.. A minimalistic example works on localhost without any issues. When i publish to azure however i get following error in my console:

`Firefox can’t establish a connection to the server at wss://****.azurewebsites.net/. WebSocketSubject.js:91`

I have enabled Websockets in my app-config on Azure.

This is my socket-code: 
```
var server = http.Server(app);
//socket-connection
const wss = new WebSocket.Server({server});

server.listen(8070, () => {
  console.log("Listening on " + port)
});


wss.on('connection', (socket) => {
  console.log('a user connected');
  socket.on('message', (msg) => {
    console.log(msg)
    socket.send(JSON.stringify({hey:'you'}))
  })
});
```
 

#### Reproducible in:

- version:
- Node.js version(s): Node 12
- OS version(s): Linux Ubuntu

#### Steps to reproduce:

1.

2.

3.

#### Expected result:
To work on Appservice hosted on Azure

#### Actual result:
`Firefox can’t establish a connection to the server at wss://****.azurewebsites.net/. WebSocketSubject.js:91`

#### Attachments:
Curl command response: 

* TCP_NODELAY set
* Connected to *******.azurewebsites.net (20.40.202.6) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.azurewebsites.net
*  start date: Sep 28 19:00:01 2020 GMT
*  expire date: Sep 28 19:00:01 2021 GMT
*  subjectAltName: host "********.azurewebsites.net" matched cert's "*.azurewebsites.net"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 01
*  SSL certificate verify ok.
> GET /socket.io/?EIO=4 HTTP/1.1
> Host: *********.azurewebsites.net
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Server: Kestrel
< WWW-Authenticate: Bearer realm="********.azurewebsites.net" authorization_uri="https://login.windows.net/<tenant>/oauth2/authorize" resource_id="<resource>"
< Date: Tue, 22 Jun 2021 05:56:15 GMT
< Content-Length: 0
< 
* Connection #0 to host *******.azurewebsites.net left intact

WS-object. logged from server

```
2021-06-22T10:32:03.607083960Z WebSocketServer {
2021-06-22T10:32:03.607778187Z   _events: [Object: null prototype] {},
2021-06-22T10:32:03.607788487Z   _eventsCount: 0,
2021-06-22T10:32:03.607792387Z   _maxListeners: undefined,
2021-06-22T10:32:03.607796088Z   _server: Server {
2021-06-22T10:32:03.607799588Z     insecureHTTPParser: undefined,
2021-06-22T10:32:03.607802988Z     _events: [Object: null prototype] {
2021-06-22T10:32:03.607806488Z       request: [EventEmitter],
2021-06-22T10:32:03.607809888Z       connection: [Function: connectionListener],
2021-06-22T10:32:03.607813288Z       listening: [Function: bound emit],
2021-06-22T10:32:03.607816688Z       error: [Function: bound emit],
2021-06-22T10:32:03.607830289Z       upgrade: [Function: upgrade]
2021-06-22T10:32:03.607834689Z     },
2021-06-22T10:32:03.607839789Z     _eventsCount: 5,
2021-06-22T10:32:03.607843289Z     _maxListeners: undefined,
2021-06-22T10:32:03.607846690Z     _connections: 0,
2021-06-22T10:32:03.607850090Z     _handle: null,
2021-06-22T10:32:03.607853490Z     _usingWorkers: false,
2021-06-22T10:32:03.607856790Z     _workers: [],
2021-06-22T10:32:03.607860190Z     _unref: false,
2021-06-22T10:32:03.607863590Z     allowHalfOpen: true,
2021-06-22T10:32:03.607866890Z     pauseOnConnect: false,
2021-06-22T10:32:03.607870291Z     httpAllowHalfOpen: false,
2021-06-22T10:32:03.607880791Z     timeout: 120000,
2021-06-22T10:32:03.607884191Z     keepAliveTimeout: 5000,
2021-06-22T10:32:03.607887191Z     maxHeadersCount: null,
2021-06-22T10:32:03.607890191Z     headersTimeout: 60000,
2021-06-22T10:32:03.607893191Z     [Symbol(IncomingMessage)]: [Function: IncomingMessage],
2021-06-22T10:32:03.607896292Z     [Symbol(ServerResponse)]: [Function: ServerResponse],
2021-06-22T10:32:03.607899292Z     [Symbol(kCapture)]: false,
2021-06-22T10:32:03.607902292Z     [Symbol(asyncId)]: -1
2021-06-22T10:32:03.607905292Z   },
2021-06-22T10:32:03.607908392Z   _removeListeners: [Function: removeListeners],
2021-06-22T10:32:03.607911392Z   clients: Set {},
2021-06-22T10:32:03.607914492Z   options: {
2021-06-22T10:32:03.607917492Z     maxPayload: 104857600,
2021-06-22T10:32:03.607920493Z     perMessageDeflate: false,
2021-06-22T10:32:03.607923493Z     handleProtocols: null,
2021-06-22T10:32:03.607926493Z     clientTracking: true,
2021-06-22T10:32:03.607929493Z     verifyClient: null,
2021-06-22T10:32:03.607932493Z     noServer: false,
2021-06-22T10:32:03.607935393Z     backlog: null,
2021-06-22T10:32:03.607938593Z     server: Server {
2021-06-22T10:32:03.607941593Z       insecureHTTPParser: undefined,
2021-06-22T10:32:03.607944593Z       _events: [Object: null prototype],
2021-06-22T10:32:03.607947694Z       _eventsCount: 5,
2021-06-22T10:32:03.607950694Z       _maxListeners: undefined,
2021-06-22T10:32:03.607953694Z       _connections: 0,
2021-06-22T10:32:03.607956594Z       _handle: null,
2021-06-22T10:32:03.607959594Z       _usingWorkers: false,
2021-06-22T10:32:03.607962594Z       _workers: [],
2021-06-22T10:32:03.607965594Z       _unref: false,
2021-06-22T10:32:03.607968594Z       allowHalfOpen: true,
2021-06-22T10:32:03.607971495Z       pauseOnConnect: false,
2021-06-22T10:32:03.607974495Z       httpAllowHalfOpen: false,
2021-06-22T10:32:03.607977495Z       timeout: 120000,
2021-06-22T10:32:03.607980495Z       keepAliveTimeout: 5000,
2021-06-22T10:32:03.607983395Z       maxHeadersCount: null,
2021-06-22T10:32:03.607986395Z       headersTimeout: 60000,
2021-06-22T10:32:03.607989395Z       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
2021-06-22T10:32:03.607992395Z       [Symbol(ServerResponse)]: [Function: ServerResponse],
2021-06-22T10:32:03.607995495Z       [Symbol(kCapture)]: false,
2021-06-22T10:32:03.607998596Z       [Symbol(asyncId)]: -1
2021-06-22T10:32:03.608001496Z     },
2021-06-22T10:32:03.608007396Z     host: null,
2021-06-22T10:32:03.608010596Z     path: null,
2021-06-22T10:32:03.608013596Z     port: null
2021-06-22T10:32:03.608016596Z   },
2021-06-22T10:32:03.608019596Z   [Symbol(kCapture)]: false
2021-06-22T10:32:03.608022697Z }
```

**Comment by lpinca** [comment]
> GET /socket.io/?EIO=4 HTTP/1.1

Are you using Socket.IO as a client to connect to a plain WebSocket server? Socket.IO is not a WebSocket client.
What happens if you run the following code?

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://****.azurewebsites.net/');

ws.on('open', function () {
  console.log('open');
});
```

**Comment by kimrunar** [comment]
Im using rxjs-websocket on my angular-client; 
import { webSocket, WebSocketSubject } from 'rxjs/webSocket';

myWebSocket = webSocket('wss://***.azurewebsites.net/')

**Comment by kimrunar** [comment]
i get
     throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 401
    at ClientRequest.<anonymous> (/home/kim/Desktop/Development/service_madmin/madmin_service/node_modules/ws/lib/websocket.js:604:7)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake

**Comment by lpinca** [comment]
The server is responding with 401. It means that you are not even hitting the WebSocket server, probably because a proxy does not forward the request due to lack of authorization.

**Comment by kimrunar** [comment]
The code you provided, is that supposed to be clientside?

**Comment by lpinca** [comment]
Yes, it's a Node.js client.

**Comment by kimrunar** [comment]
Hm. how do i authorize it? the endpoint is protected by AAD-tokens

**Comment by lpinca** [comment]
Try passing an authorization header or a cookie. It depends on where the server searches for it.

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://****.azurewebsites.net/', {
  headers: {
    Authorization: Bearer <token>
  }
});

ws.on('open', function () {
  console.log('open');
});
```

Anyway this is not an issue in `ws`.

**Comment by kimrunar** [comment]
Maybe its not an _issue_ in ws, but it lacks the proper documentation for this usecase i think.

**Comment by lpinca** [comment]
The documentation tells you how to use the library. Documenting how to integrate it with external services is out of the scope of the project and inflexible because there are too many of them. This kind of documentation should be provided by the vendor of the external service, in this specific case, Microsoft.

**Comment by lpinca** [comment]
To make my point clearer, see https://developer.mozilla.org/en-US/docs/Web/API/WebSocket. That documentation does not cover how to connect to an Azure endpoint protected by ADD-tokens because that is out of the scope of the documentation.

I'm closing this as answered. Discussion can continue if needed.
