### ISSUE TITLE
TypeError: Class constructor WebSocketServer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Arcanorum** [websockets/ws#2015]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When trying to extend the WebSocketServer class with custom functionality while using TypeScript, TS throws a type error.

Example:
test.ts
```ts
import { WebSocketServer } from 'ws';

class CustomWebSocketServer extends WebSocketServer { }

const wss = new CustomWebSocketServer({ port: 1234 });

export default wss;
```
Run with `npx ts-node test.ts`

Works fine with JS.
test.js
```js
const { WebSocketServer } = require('ws');

class CustomWebSocketServer extends WebSocketServer { }

const wss = new CustomWebSocketServer({ port: 1234 });

module.exports = wss;
```
Run with `node test.ts`

### ws version

8.4.2

### Node.js Version

16.13.0

### Expected result

Be able to extend WebSocketServer class using TypeScript.

### Actual result

```
TypeError: Class constructor WebSocketServer cannot be invoked without 'new'
    at new CustomWebSocketServer (/home/user/bug-demo/test.ts:22:42)
    at Object.<anonymous> (/home/user/bug-demo/test.ts:5:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/user/bug-demo/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/user/bug-demo/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (/home/user/bug-demo/node_modules/ts-node/src/bin.ts:331:12)
```

**Comment by Arcanorum** [comment]
Problem was the `target` set in `tsconfig.json`. Changing from "ES5" to "ES6" fixed this.

```json
"compilerOptions": {
   "target": "ES6" // Won't work with "ES5".
}
```
