### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by richconner** [websockets/ws#2019]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

node:events:498
      throw er; // Unhandled 'error' event
      ^
  
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/home/ubuntu/server/node_modules/ws/lib/receiver.js:189:14)
    at Receiver.startLoop (/home/ubuntu/server/node_modules/ws/lib/receiver.js:136:22)
    at Receiver._write (/home/ubuntu/server/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/home/ubuntu/server/node_modules/ws/lib/websocket.js:1231:35)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/home/ubuntu/server/node_modules/ws/lib/websocket.js:1117:13)
    at Receiver.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}

**Comment by richconner** [comment]
I am reporting this on behalf of my development teammate, Consty.

We have a send() function in a try/catch block, 
We also process the "error" event

**Comment by lpinca** [comment]
Add a listener for the `'error'` event on the `WebSocket` instance.

```js
wss.on('connection', function connection(ws) {
  ws.on('error', console.error);

  // ...
});
```

**Comment by lpinca** [comment]
See also https://github.com/websockets/ws/issues/1777, https://github.com/websockets/ws/issues/1825, etc.

**Comment by suinswofi** [comment]
> Add a listener for the `'error'` event on the `WebSocket` instance.
> 
> ```js
> wss.on('connection', function connection(ws) {
>   ws.on('error', console.error);
> 
>   // ...
> });
> ```

We process the error, but I think there was a race condition due to using an async function for the connection event and calling await on another call. See example below.

`wss.on('connection', async function connection(ws) {
  await myfunction();   

  // this event isn't attached until after myfunction finishes, and if an error is thrown it will crash the library
  ws.on('error', console.error);

  // ...
});`

May want to handle error silently if one isn't already attached to the websocket.

**Comment by lpinca** [comment]
> May want to handle error silently if one isn't already attached to the websocket.

No, the process must exit if an error is emitted and there is no listener for the `'error'` event as per https://nodejs.org/api/events.html#error-events.

**Comment by suinswofi** [comment]
> > May want to handle error silently if one isn't already attached to the websocket.
> 
> No, the process must exit if an error is emitted and there is no listener for the `'error'` event as per https://nodejs.org/api/events.html#error-events.

Understood. My recommendation then would be to update your documentation to be careful when using async functions attached to ws events (specifically connection) since a race condition exists that will effectively crash the entire program. All the discussions I've seen state that it's safe to use them, but definitely not for the connection event at a minimum. That's what was killing us.

**Comment by lpinca** [comment]
>All the discussions I've seen state that it's safe to use them, but definitely not for the connection event at a minimum.

It's ok. You only have to add the listener of the `'error'` event before any `await`.
