### ISSUE TITLE
Websocket Client invalid UTF-8 sequence

### ISSUE THREAD

**Issue by rstrouse** [websockets/ws#2047]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I have a nodejs application that is receiving data from an array of ESP-8266 devices.  So there is one socket per ESP.  Unfortunately, I get an occasional `invalid UTF-8 sequence` that crashes my server and brings down the whole lot.  I have tried several different ways to catch the exception but it is initiated in the receiver code.  Below is the stack trace.
```
[5/23/2022, 3:13:25 PM] info: Connecting ESP to socket ws://ESP-D6EC16:8080
[5/23/2022, 3:13:32 PM] info: Connection attempt 1 to ws://ESP-D6EC16:8080

C:\tagyoureit\lushThumb\node_modules\ws\lib\receiver.js:519
          return error(
                 ^
Error: Invalid WebSocket frame: invalid UTF-8 sequence
    at Receiver.dataMessage (C:\tagyoureit\lushThumb\node_modules\ws\lib\receiver.js:519:18)
    at Receiver.getData (C:\tagyoureit\lushThumb\node_modules\ws\lib\receiver.js:446:17)
    at Receiver.startLoop (C:\tagyoureit\lushThumb\node_modules\ws\lib\receiver.js:148:22)
    at Receiver._write (C:\tagyoureit\lushThumb\node_modules\ws\lib\receiver.js:83:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at Socket.socketOnData (C:\tagyoureit\lushThumb\node_modules\ws\lib\websocket.js:1254:35)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Press any key to continue...
```

I added the `skipUTFValidation:true` flag but that didn't help.  It can run for days or just a few minutes before the exception is thrown.  If I could just catch the exception so that it doesn't topple the world then I would simply restart the sensor platform and be off with it.  But the exception is thrown in a place where I cannot seem to catch it.  

All of these devices are connected via WiFi so they can frequently disconnect and reconnect on their own.  Each time I get a disconnect I terminate the old socket and create a new one.  I cannot seem to find any status that tells me whether the socket is still alive or any way to release resources.

Any help would be appreciated.

### ws version

current

### Node.js Version

v12,20.2

### System

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 15.46 GB / 31.68 GB

**Comment by lpinca** [comment]
The flag name is `skipUTF8Validation` not `skipUTFValidation`. Anyway you can handle error by adding a listener for the `'error'` event on the `WebSocket` object.

```js
const http = require('http');
const { Sender, WebSocketServer } = require('ws');

const server = new WebSocketServer({ port: 0 }, function () {
  const request = http.get({
    port: server.address().port,
    headers: {
      Connection: 'Upgrade',
      Upgrade: 'websocket',
      'Sec-WebSocket-Key': 'dGhlIHNhbXBsZSBub25jZQ==',
      'Sec-WebSocket-Version': 13
    }
  });

  request.on('upgrade', function (response, socket) {
    const data = Buffer.from([0xf8]);
    const frame = Buffer.concat(
      Sender.frame(data, { fin: true, mask: true, opcode: 0x01 })
    );

    socket.write(frame);
  });
});

server.on('connection', function (ws) {
  ws.on('error', console.error);
});
```

**Comment by lpinca** [comment]
> I guess what I am asking is should I be removing the listeners that I attached to the socket on destroy?

You should not remove listeners until the `'close'` event is emitted.

**Comment by lpinca** [comment]
I'm closing this as answered.
