### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers

### ISSUE THREAD

**Issue by allan-bonadio** [websockets/ws#2063]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I get this message on the server side, when I do a response.send() on an unrelated (different port numbers) express server, after the ws is open and sending messages (not sure on the timing for that...)

message with traceback:
(node:45980) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at IncomingMessage.fresh (/Volumes/flores/GLMR5/gscripts/pairResolve/node_modules/express/lib/request.js:444:41)
    at ServerResponse.send (/Volumes/flores/GLMR5/gscripts/pairResolve/node_modules/express/lib/response.js:189:10)
    at /Volumes/flores/GLMR5/gscripts/pairResolve/server.js:99:12
    at /Volumes/flores/GLMR5/gscripts/pairResolve/server.js:53:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
[... more threads ...]

node command: the first message said to turn on --trace-deprecation, then I got the detailed one above.
node --inspect-brk --trace-deprecation server.js

client side: Chrome for Mac: Version 103.0.5060.53 (Official Build) (x86_64)
both sides, same machine: Mac OSX Catalina version 10.15.7 (19H1922)

Otherwise, things seem to work OK; not critical or anything, just thought you should know.

### ws version

8.8.0

### Node.js Version

v16.15.0

### System

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 1.51 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash

### Expected result

works with no deprecation warnings

### Actual result

deprecation warning

**Comment by lpinca** [comment]
From the stack trace it seems the waring is coming from `express`, not `ws`.

```
at IncomingMessage.fresh (/Volumes/flores/GLMR5/gscripts/pairResolve/node_modules/express/lib/request.js:444:41)
```

**Comment by lpinca** [comment]
See https://github.com/expressjs/express/blob/4.13.4/lib/request.js#L444

**Comment by allan-bonadio** [comment]
aha!  thank you!

**Comment by allan-bonadio** [comment]
submitted ticket to express
https://github.com/expressjs/express/issues/4947
