### ISSUE TITLE
Can't listen to the same port with different paths

### ISSUE THREAD

**Issue by agektmr** [websockets/ws#21]
Following code fails:

``` javascript
var WebSocketServer = require('ws').Server,
    a = new WebSocketServer({port:8080, path:'/a'}), 
    b = new WebSocketServer({port:8080, path:'/b'});
return;
```

I receive error as follows:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:632:11)
    at Array.1 (net.js:733:26)
    at EventEmitter._tickCallback (node.js:192:40)
```

on node.js 0.6.6 with latest ws.

**Comment by physiii** [comment]
Can you link to the test case you are referring to?

I need to launch a server on the same port with different paths. I don't want to use a proxy for this.
