### ISSUE TITLE
App crashes for: RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by ile** [websockets/ws#2170]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm getting this error quite a lot, and the app crashes for it:

```
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/home/ile/src/sc2/aamuapp/node_modules/ws/lib/receiver.js:203:14)
    at Receiver.startLoop (/home/ile/src/sc2/aamuapp/node_modules/ws/lib/receiver.js:149:22)
    at Receiver._write (/home/ile/src/sc2/aamuapp/node_modules/ws/lib/receiver.js:87:10)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at Receiver.Writable.write (node:internal/streams/writable:494:10)
    at Socket.socketOnData (/home/ile/src/sc2/aamuapp/node_modules/ws/lib/websocket.js:1286:35)
    at Socket.emit (node:events:515:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Socket.Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
 {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}
```

I'm using this, but it doesn't seem to help here: 

```javascript
  wss.on('connection', function (ws) {
    ws.on('error', console.error);
```

How can I catch this error, so that the whole app wouldn't crash?

### ws version

8.14.2

### Node.js Version

v21.1.0

**Comment by lpinca** [comment]
> How can I catch this error, so that the whole app wouldn't crash?

Do not remove the `'error'` listener from the `WebSocket` object until the `'close'` event is emitted.

**Comment by lpinca** [comment]
You can reproduce the error like this.

```js
const WebSocket = require('ws');

const server = new WebSocket.WebSocketServer({ port: 0 }, function () {
  const websocket = new WebSocket(`ws://localhost:${server.address().port}`);

  websocket.on('open', function () {
    const chunk = Buffer.from('a180', 'hex');

    websocket._socket.write(chunk);
  });
});

server.on('connection', function (websocket) {
  websocket.on('error', console.error);
});
```

The process does not exit.

**Comment by lpinca** [comment]
Duplicate of https://github.com/websockets/ws/issues/2151 and https://github.com/websockets/ws/issues/2098.

**Comment by ile** [comment]
Ok, will try again, thanks. Maybe I did something wrong.
