### ISSUE TITLE
TypeError: Cannot read property 'fragmentedOperation' of null

### ISSUE THREAD

**Issue by swither** [websockets/ws#283]
Hi!

My node.js server keeps crashing with the following error:

/home/ubuntu/node_modules/ws/lib/Receiver.js:228
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (/home/ubuntu/node_modules/ws/lib/Receiver.js:228:18)
    at Receiver.opcodes.1.finish (/home/ubuntu/node_modules/ws/lib/Receiver.js:400:12)
    at Receiver.<anonymous> (/home/ubuntu/node_modules/ws/lib/Receiver.js:378:33)
    at Receiver.add (/home/ubuntu/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/home/ubuntu/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7

I'm clueless to what could be causing this and was hoping someone might have an idea!

**Comment by amark** [comment]
I just hit this when I was doing stress testing on my server. But I think it might be related to me reloading FireFox while operations are still happening (see https://bugzilla.mozilla.org/show_bug.cgi?id=712329 ) that might be triggering stuff. I am using close() onbeforeunload in FF though.

**Comment by lpinca** [comment]
Closing this as I think the issue has been fixed, please comment or reopen if it still happens.
