### ISSUE TITLE
CryptoStream is not writable

### ISSUE THREAD

**Issue by shacharz** [websockets/ws#302]
I"m getting this error on my node instance every few hours, anyone encountered it?
Error: CryptoStream is not writable
    at CleartextStream.CryptoStream.write (tls.js:241:11)
    at Sender.frameAndSend (/opt/peer5_ws/node_modules/ws/lib/Sender.js:174:22)
    at Sender.close (/opt/peer5_ws/node_modules/ws/lib/Sender.js:43:8)
    at WebSocket.close (/opt/peer5_ws/node_modules/ws/lib/WebSocket.js:101:18)
    at Object.module.exports.instance.start.expireFunction (/opt/peer5_ws/core/t                                                                                        ransport/WebSocketServer.js:17:32)
    at exports.monitor.oldSessions (/opt/peer5_ws/core/util/session-manager.js:1                                                                                        4:27)
    at Array.forEach (native)
    at Timer.expire (/opt/peer5_ws/core/util/session-manager.js:13:34)
    at Timer.asyncWrap (/opt/peer5_ws/node_modules/newrelic/node_modules/continu                                                                                        ation-local-storage/node_modules/async-listener/glue.js:295:29)
    at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
error: Forever detected script exited with code: 1
error: Forever restarting script for 1 time

**Comment by zz85** [comment]
getting similar errors from testing 0.6.5 in production. could it be related to per-message deflate issues @nkzawa?

**Comment by zz85** [comment]
these errors seem suppressed when `send(data, { compress: false; })` is used, it could be possible that some browsers are causing this error.

**Comment by lpinca** [comment]
I close this as a long time has passed and hopefully this is no longer an issue. Please reopen or comment if needed.
