### ISSUE TITLE
null exception in endPacket()

### ISSUE THREAD

**Issue by forTAT** [websockets/ws#319]
Hi,
I currently get this error:

```
TypeError: Cannot read property 'fragmentedOperation' of null
at Receiver.endPacket (C:\node_modules\ws\lib\Receiver.js:228:18)
at Receiver.opcodes.1.finish (C:\node_modules\ws\lib\Receiver.js:400:12)
at Receiver.<anonymous> (C:\node_modules\ws\lib\Receiver.js:378:33)
at Receiver.add (C:\node_modules\ws\lib\Receiver.js:93:24)
at Socket.firstHandler (C:\node_modules\ws\lib\WebSocket.js:678:22)
at Socket.EventEmitter.emit (events.js:95:17)
at Socket.<anonymous> (_stream_readable.js:746:14)
at Socket.EventEmitter.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:408:10)
at emitReadable (_stream_readable.js:404:5)
```

As far as I could find out, this happens after endPacket() in opcodes.1.finish is called. In the endpacket() function, this.state is null.

I am really not sure why this happens. One scenario for the occurrence of this error is when the server calls ws.send() and right after I refresh the client's browser page which results in a new connection.

Can anybody tell me how to avoid this error?

**Comment by lpinca** [comment]
Closing this as the issue report is very old. Please comment or reopen if the issue still happens.

**Comment by oasiz** [comment]
Hi,

I know this is old but I've just had the same.

```
C:\Users\Administrator\Desktop\node\node_modules\ws\lib\Receiver.js:243
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true);
                 ^

TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (C:\Users\Administrator\Desktop\node\node_modules\ws\l
ib\Receiver.js:243:18)
    at Receiver.opcodes.8.finish (C:\Users\Administrator\Desktop\node\node_modul
es\ws\lib\Receiver.js:604:12)
    at Receiver.<anonymous> (C:\Users\Administrator\Desktop\node\node_modules\ws
\lib\Receiver.js:566:33)
    at Receiver.add (C:\Users\Administrator\Desktop\node\node_modules\ws\lib\Rec
eiver.js:91:24)
    at Socket.firstHandler (C:\Users\Administrator\Desktop\node\node_modules\ws\
lib\WebSocket.js:759:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

No idea what's triggered it though? Let me know if you require more info!

**Comment by lpinca** [comment]
@oasiz I suggest you to use `ws@3`.
