### ISSUE TITLE
Error('not opened') on reloading the page

### ISSUE THREAD

**Issue by pmcalabrese** [websockets/ws#322]
I'm trying to replicate the simple example in the readme. But when i refresh the page i get the following error...

```
/usr/lib/node_modules/ws/lib/WebSocket.js:187
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/usr/lib/node_modules/ws/lib/WebSocket.js:187:16)
    at /var/lib/cloud9/eventrecorder/server.js:22:7
    at f.digitalRead.readFile (/usr/lib/node_modules/bonescript/index.js:355:13)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

Any suggestions?

**Comment by lpinca** [comment]
You can use a callback to catch this error:

```js
ws.send(data, function data(err) {
  if (err) handleError(err);
});
```
