### ISSUE TITLE
Explanation for "Error: not opened"

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#394]
Hello guys

This ticket is rather a request for an explanation of an error I do not fully understand. Do you think you could either add more context to the error or examine the following stack trace and tell me what it could be?

```
Stack
Error: not opened
at WebSocket.send (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:181:16)
at DestroyableTransform.socketWrite [as _transform] (/var/www/videomail/production/source/node_modules/websocket-stream/index.js:35:12)
at DestroyableTransform.Transform._read (/var/www/videomail/production/source/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
at DestroyableTransform.Transform._write (/var/www/videomail/production/source/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
at doWrite (/var/www/videomail/production/source/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
at writeOrBuffer (/var/www/videomail/production/source/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
at DestroyableTransform.Writable.write (/var/www/videomail/production/source/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
at writeCommand (/var/www/videomail/production/source/src/socket/items/client.js:204:16)
at makeVideos (/var/www/videomail/production/source/src/socket/commands/stop.js:35:24)
at fn (/var/www/videomail/production/source/node_modules/async/lib/async.js:641:34)
```

Many thanks!

**Comment by binarykitchen** [comment]
Here you go! :)
