### ISSUE TITLE
Error: unexpected server response (400)  Works from Windows to Unix not Unix to Unix

### ISSUE THREAD

**Issue by chussenet** [websockets/ws#397]
I can connect from my windows 7 box to a unix server through websocket, however running the same code on a unix box generates the following error :

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: unexpected server response (400)
    at ClientRequest.<anonymous> (/home/chussenet/treetable/web/node_modules/ws/lib/WebSocket.js:585:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)
    at Socket.socketOnData [as ondata](http.js:1583:20)
    at TCP.onread (net.js:527:27)
## Source CODE

var WebSocket = require('ws');
var ws = new WebSocket('ws://unixHostname:port' );

ws.on('open',function(){
    console.log("Connected");
});

**Comment by melvincarvalho** [comment]
Same issue

    var WebSocket = require('ws');

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

    var ws = new WebSocket('wss://localhost:443/');

    ws.on('open', function open() {
      console.log('connected');
      ws.send(Date.now().toString(), {mask: true});
    });

    ws.on('close', function close() {
      console.log('disconnected');
    });

    ws.on('message', function message(data, flags) {
      console.log('Roundtrip time: ' + (Date.now() - parseInt(data)) + 'ms', flags);
    });

Gives

    node test.js 

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: unexpected server response (400)
        at ClientRequest.response (/var/www/ld/test/node_modules/ws/lib/WebSocket.js:674:15)
        at ClientRequest.g (events.js:180:16)
        at ClientRequest.EventEmitter.emit (events.js:95:17)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
        at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
        at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
        at CleartextStream.read [as _read] (tls.js:511:12)
        at CleartextStream.Readable.read (_stream_readable.js:320:10)
        at EncryptedStream.write [as _write] (tls.js:366:25)
        at doWrite (_stream_writable.js:223:10)

Or

    node test.js 

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: unexpected server response (403)
        at ClientRequest.response (/var/www/ld/test/node_modules/ws/lib/WebSocket.js:674:15)
        at ClientRequest.g (events.js:180:16)
        at ClientRequest.EventEmitter.emit (events.js:95:17)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
        at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
        at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
        at CleartextStream.read [as _read] (tls.js:511:12)
        at CleartextStream.Readable.read (_stream_readable.js:320:10)
        at EncryptedStream.write [as _write] (tls.js:366:25)
        at doWrite (_stream_writable.js:223:10)

**Comment by shapiroisme** [comment]
any update?

**Comment by lpinca** [comment]
Is this still an issue?

**Comment by lpinca** [comment]
Closing due to inactivity, please reopen if needed.

**Comment by misha-panyushkin** [comment]
Same problem. 
WS Version: "^1.1.1"

`

        const WebSocket = require('ws')
        this.ws = new WebSocket(URL)
        this.ws.on('open', () => this.subscribe())
        this.ws.on('message', (data, flags) => this.onMessage(data, flags))
        this.ws.on('close', () => {
            setTimeout(() => this.connect(), 1000)
        })
`

Sometimes gives:
![image](https://cloud.githubusercontent.com/assets/890700/21830563/9af2f5c2-d7ae-11e6-842f-9b83aecae883.png)

**Comment by lpinca** [comment]
@misha-panyushkin you get a 502 error. If you are using a proxy on your server, like nginx, it's likely that the proxy cannot forward the request.

**Comment by misha-panyushkin** [comment]
@lpinca same today:
```
Error: unexpected server response (404)
16:21:22 0|app      |     at ClientRequest.response (/usr/src/app/node_modules/ws/lib/WebSocket.js:719:15)
16:21:22 0|app      |     at ClientRequest.g (events.js:260:16)
16:21:22 0|app      |     at emitOne (events.js:77:13)
16:21:22 0|app      |     at ClientRequest.emit (events.js:169:7)
16:21:22 0|app      |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:427:21)
16:21:22 0|app      |     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
16:21:22 0|app      |     at TLSSocket.socketOnData (_http_client.js:317:20)
16:21:22 0|app      |     at emitOne (events.js:77:13)
16:21:22 0|app      |     at TLSSocket.emit (events.js:169:7)
16:21:22 0|app      |     at readableAddChunk (_stream_readable.js:146:16)
16:21:22 0|app      |     at TLSSocket.Readable.push (_stream_readable.js:110:10)
16:21:22 0|app      |     at TLSWrap.onread (net.js:523:20)
```

**Comment by lpinca** [comment]
@misha-panyushkin the server answers with a 404 in this case and that's obviously wrong. It looks like a server / proxy issue to me.

**Comment by ricardofbarros** [comment]
@lpinca I think what they are saying is that it shouldn't throw.

If that's the case @misha-panyushkin just add an error event handler ;) and it shouldn't throw anymore.

```
    this.ws.on('error', (err) => {
        console.log('Fluffy error', err)
    })
```

**Comment by markito12** [comment]
Error: unexpected server response (400)
    at ClientRequest.response (C:\Users\auxfr\Desktop\ChatBot_Project-master\node_modules\ws\lib\WebSocket.js:719:15)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
