### ISSUE TITLE
Unable to send big files

### ISSUE THREAD

**Issue by wilhelmmatilainen** [websockets/ws#457]
I'm trying to upload files bigger than the maximum size of a buffer in node.js using socket.io.
When using chromium to upload a file larger than 1Gb, chromium will crash before node.js.
When using firefox to upload this same file, node.js will crash with the error trace below.
Instead of allocating a very large buffer, there should be some piping mechanism to allow a continuous stream or a large file being uploaded.

``` javascript
// Client
var reader = new FileReader();                                       

reader.onload = function(e) {
    socket.emit('upload', e.target.result, function(error, data) {                 
        if (error) {                                                   
            fail(new Error(error));                                      
        } else if (success)                                                  
            success(data);                                             
    });
};                                       

reader.readAsArrayBuffer(file); // file == input file from a form
```

Maximum buffer size:
http://nodejs.org/docs/v0.11.5/api/smalloc.html#smalloc_smalloc_kmaxlength

```
Server node.js with socket.io
app:trace RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:72:11)
    at BufferPool.get (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/BufferPool.js:38:18)
    at Receiver.allocateFromPool (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:170:83)
    at Receiver.expectData (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:150:28)
    at Receiver.expectHandler (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:426:16)
    at Receiver.add (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/srv/http/app/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by Auxolust** [comment]
Not to snipe, or push my own product, but I have an implementation of a websocket that can support streaming if you don't find an answer using ws

**Comment by nkzawa** [comment]
It seems you are using socket.io then check https://github.com/nkzawa/socket.io-stream

**Comment by lpinca** [comment]
You can use `ws` to stream the data for example with something like this:

``` js
(function read(readable) {
  const chunk = readable.read();

  if (chunk === null) {
    ws.send(chunk, { fin: true });
    return
  }

  ws.send(chunk, { fin: false }, (err) => {
    if (err) return handleError(err);

    read(readable);
  });
})(readable);
```

but if files are bigger than the maximum allowed buffer size that won't help much as all chunks are merged together when the stream ends to rebuild the message.

You have to split the files into smaller parts and send them individually.
