### ISSUE TITLE
ws.close() and ws.terminate() throw Uncaught Error: socket hang up

### ISSUE THREAD

**Issue by olalonde** [websockets/ws#503]
I'm getting the following error when trying to close a websocket connection:

``` javascript
  Uncaught Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
   at TLSSocket.socketOnEnd (_http_client.js:300:23)
   at _stream_readable.js:908:16
```

**Comment by lpinca** [comment]
Is this still an issue?

**Comment by olalonde** [comment]
No idea... feel free to close :)

**Comment by lpinca** [comment]
Ok, please reopen if needed.
Thanks!
