### ISSUE TITLE
uncaught unspecified error

### ISSUE THREAD

**Issue by klinquist** [websockets/ws#535]
Getting a bunch of crashes over the past 48 hours that I haven't seen previously.  Not sure what has changed on my side.  Node 0.12.5.  Simply sending text data back and forth from iOS.

Error: Uncaught, unspecified "error" event.
    at Error (native)
    at WebSocket.emit (events.js:87:13)
    at Receiver.onerror (/data/myScript/node_modules/ws/lib/WebSocket.js:832:10)
    at Receiver.error (/data/myScript/node_modules/ws/lib/Receiver.js:317:8)
    at Receiver.processPacket (/data/myScript/node_modules/ws/lib/Receiver.js:191:12)
    at Receiver.add (/data/myScript/node_modules/ws/lib/Receiver.js:91:24)
    at firstHandler (/data/myScript/node_modules/ws/lib/WebSocket.js:774:22)
    at firstHandler (/data/myScript/node_modules/ws/lib/WebSocket.js:774:22)
    at firstHandler (/data/myScript/node_modules/ws/lib/WebSocket.js:774:22)
    at firstHandler (/data/myScript/node_modules/ws/lib/WebSocket.js:774:22)
    at firstHandler (/data/myScript/node_modules/ws/lib/WebSocket.js:774:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by woverton** [comment]
Did you get this sorted in the end?

**Comment by klinquist** [comment]
Nope.   I put in some code to catch errors, but it's not giving me any insight.

**Comment by woverton** [comment]
Do you think you could try an isolate some code which causes the error and post it in this issue?

Also, what IOS client are you using?

**Comment by klinquist** [comment]
The code I inserted was in lib/WebSocket.js:71
this.on('error', function(a,b) {console.error('[WebSocket Error!]',a,b)})

What I'm getting out of that is:
[WebSocket Error!] reserved fields must be empty 1002

We're using IPWorks WS:
http://www.nsoftware.com/ipworks/ws/

**Comment by lpinca** [comment]
It seems that you are receiving frames that have reserved bits set to on. This is probably an issue with the client sending malformed frames.
I close this, please comment or reopen if needed.
