### ISSUE TITLE
Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by mkamioner** [websockets/ws#539]
Hi!

I am using the library and I came across this somewhat random error. Has anyone else experienced this? Any idea how I can stop it from happening agan?

It only happened once and I am not sure as to why.

```
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at WebSocket.emit (events.js:87:13)
    at Receiver.onerror (/media/ephemeral0/myProject/node_modules/ws/lib/WebSocket.js:833:10)
    at Receiver.error (/media/ephemeral0/myProject/node_modules/ws/lib/Receiver.js:317:8)
    at Receiver.processPacket (/media/ephemeral0/myProject/node_modules/ws/lib/Receiver.js:191:12)
    at Receiver.add (/media/ephemeral0/myProject/node_modules/ws/lib/Receiver.js:91:24)
    at firstHandler (/media/ephemeral0/myProject/node_modules/ws/lib/WebSocket.js:768:22)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by mkamioner** [comment]
I listened to the error event and this no longer happened :-)
