### ISSUE TITLE
Receiver.error: Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by zwz** [websockets/ws#581]
I am using ws@0.8.0. 
Here is the error log:

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
  at TypeError (<anonymous>:null:null)
  at WebSocket.emit (events.js:74:15)
  at Receiver.onerror (/home/admin/dt-server/node_modules/ws/lib/WebSocket.js:833:10)
  at Receiver.error (/home/admin/dt-server/node_modules/ws/lib/Receiver.js:317:8)
  at Receiver.processPacket (/home/admin/dt-server/node_modules/ws/lib/Receiver.js:191:12)
  at Receiver.add (/home/admin/dt-server/node_modules/ws/lib/Receiver.js:91:24)
  at Socket.firstHandler (/home/admin/dt-server/node_modules/ws/lib/WebSocket.js:775:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)

**Comment by lpinca** [comment]
This happens when there isn't a listener for the `error` event. You should add one and handle the error:

```js
wss.on('connection', (ws) => {
  ws.on('error', (err) => { // Handle the error. })
});
```
