### ISSUE TITLE
Errors from Chrome but not Firefox

### ISSUE THREAD

**Issue by greggman** [websockets/ws#591]
I'm seeing errors in Chrome. I don't know for certain this is a Chrome issue but I don't get the same errors in Firefox.  I filed a bug with the Chrome team but you might want to take a look

https://code.google.com/p/chromium/issues/detail?id=536627

Basically I made a simple test that sends 5meg strings to the server. The server checks it got the strings it expects. When running in Firefox it runs forever. When running in Chrome it crashes ws after an indeterminate amount of time. Example

```
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (invalid utf8 sequence)
    at WebSocket.emit (events.js:144:17)
    at Receiver.onerror (/Users/gregg/temp/chrome-websocket-race/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/Users/gregg/temp/chrome-websocket-race/node_modules/ws/lib/Receiver.js:321:8)
    at /Users/gregg/temp/chrome-websocket-race/node_modules/ws/lib/Receiver.js:474:20
    at /Users/gregg/temp/chrome-websocket-race/node_modules/ws/lib/Receiver.js:361:7
    at /Users/gregg/temp/chrome-websocket-race/node_modules/ws/lib/PerMessageDeflate.js:221:5
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
```

node 4.1.0
ws 0.8.0

**Comment by greggman** [comment]
The Chrome team has filed #594 based on the report above
