### ISSUE TITLE
Better handling of Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by DeepSnowNeeL** [websockets/ws#609]
Hello, when i run two node with the same port on websocket i have this exception :
Caught exception: Error: listen EADDRINUSE 0.0.0.0:1840
Error: listen EADDRINUSE 0.0.0.0:1840
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:461:9)
    at process._tickCallback (node.js:367:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)
    at node.js:972:3

I would love to have something to catch it other than process.on('uncaughtException'...
I saw a callback in WebSocketServer ctor, maybe it can be used to handle this error too ?

Thanks !

**Comment by varkor** [comment]
You should be able to catch the error with `wss.on("error", error => console.log("The server encountered an error!"));` (assuming here that `wss` is your `WebSocketServer`).

**Comment by lpinca** [comment]
What @varkor said, closing.
