### ISSUE TITLE
Websocket onError handler assumes that event is an object - can crash on certain receiver errors

### ISSUE THREAD

**Issue by inversion** [websockets/ws#622]
https://github.com/websockets/ws/blob/master/lib/Receiver.js#L190 and various other places in Receiver processPacket call `this.error` with a string as the reason. This is passed through to the WebSocket onError handler at https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L426 which assumes that the event is an object - when it tries to assign properties to the event this causes the below error:

```
event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of reserved fields (2, 3) must be empty
    at WebSocket.onError (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:190:12)
    at Receiver.add (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:95:24)
    at TLSSocket.realHandler (/app/node_modules/ourapp/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

I've reproduced this by terminating a websocket server which is proxied to using Apache 2.4 and `mod_proxy_wstunnel`.

I'm happy to try and make a PR to fix this. Would it be valid to assign string events to a .reason property of a new event object in the onError handler?

**Comment by Endromede** [comment]
` event.type = 'error';` 
`                 ^              ` 
`  TypeError: Cannot assign to read only property 'type' of reserved fields must be empty` 
`      at WebSocket.onError (/app/node_modules/ws/lib/WebSocket.js:426:16)`
i have same problem when i use websocket with proxy ( not all time ).

**Comment by rupamkhaitan** [comment]
I see this error with Nodejs 4.2.3 and ws library 0.8.1, now one of my process which is using ws library and clients are connected, suddenly we see this error

TypeError: Cannot assign to read only property 'domainEmitter' of continuation frame cannot follow current opcode
    at WebSocket.emit (events.js:136:24)
    at Receiver.onerror (/opt/cnmaestro-server/deploy/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:212:12)
    at Receiver.add (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/opt/cnmaestro-server/deploy/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)


And the process gets killed, even though our process is wrapped inside domain.run()

**Comment by rupamkhaitan** [comment]
With nodejs 4.2.4 release , this error are now easily caught by domain and doesnt kill our process.
Thanks to Nodejs 4.2.4 release

**Comment by lpinca** [comment]
Should be fixed on master, closing.
