### ISSUE TITLE
Error: Uncaught, unspecified "error" event. (reserved fields must be empty)

### ISSUE THREAD

**Issue by SzAmmi** [websockets/ws#656]
This is the code:
```javascript
var WebSocket = require('ws');
var connections = [];
var wss = new WebSocket.Server( { port: 7000, perMessageDeflate: false } );

wss.on('connection', function (conn) {
	conn.on('error', function (e) { console.log("Got an error"); console.log(e); });
	connections.push(conn);

	conn.on('message', function(msg) {
		json = JSON.parse(msg);
				for (connection of connections) {
					if (typeof connection != "undefined" && connection.readyState == connection.OPEN) {
						connection.send(json.nick + ': ' + json.message);
					}
				}
	});
});
```
A few hours later after when I ran the program I got this:
```
Error: Uncaught, unspecified "error" event. (reserved fields must be empty)
    at WebSocket.emit (events.js:144:17)
    at Receiver.onerror (/root/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/root/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/root/node_modules/ws/lib/Receiver.js:195:12)
    at Receiver.add (/root/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/root/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
How can I catch this? How can I fix this?

**Comment by JacksonTian** [comment]
What's your version? And how to reproduce quickly?

**Comment by SzAmmi** [comment]
@JacksonTian What version? I use the newest ws library.

**Comment by SzAmmi** [comment]
Added after 3rd line:
```javascript
ws.on('error', function(e) { console.log('Got an error'); });
```
and it worked.
