### ISSUE TITLE
Crashes under high load

### ISSUE THREAD

**Issue by pulviscriptor** [websockets/ws#669]
Hi.
I made client for game [agario-client](https://github.com/pulviscriptor/agario-client) using <b>ws</b>. 
Then i added [socks support](https://github.com/pulviscriptor/agario-client#socksproxy-support) using lib [socks](https://www.npmjs.com/package/socks) as recommended and users started to report crashes in my code because invalid binary data received. I do not know why data breaks. This issue is not about breaking data, but if somebody curious [here](https://github.com/pulviscriptor/agario-client/issues/56#issuecomment-171772427) is investigation on "good for investigation packet".
I think data breaks on low-quality SOCKS servers. So crashes of <b>ws</b> can be related to invalid data received.
I added event for `packetError` when my lib unable to parse binary data and crashes because of invalid data in my lib stopped, but <b>ws</b> started to crash.
## Reproducing

<sup>Disclamer: Unfortunately i don't want to share code that i use, because using it i was able to spawn over 500 bots on server and make it lag and run very slow. Don't want anybody to do that.</sup>
- OS: Windows 7 x64
- Node.JS: v0.12.2
- ws: 1.0.1
- agario-client: 1.2.4
- Script settings: 80 SOCKS, 2 bots per SOCKS (some of SOCKS are dead, there is 40-50 alive)

I spawning about 80-100 bots using 40-50 SOCKS servers.
I use this code to show load:

``` javascript
var interval = 100;
var last_interval = (+new Date);

setInterval(function(){
    var now = (+new Date);
    console.log('delay: ' + (now-last_interval-interval) + 'ms');
    last_interval = now;
}, interval);
```

On start of script delay is <b>0ms-1ms</b> but over minutes of run it increasing to over <b>100ms</b>.
Something somewhere is leaking, i do not know what, i will investigate that later, but i think you want to know this information.
The higher delay, the higher is crash chance. One time i got crash <b>2ms</b> delay, one time i got crash at over <b>1000ms</b> delay. Usually it crashes after <b>100ms-200ms</b>.
For reporting crashes i will add `try catch` block to disable crashes that i already described here. 
I will not add new lines to not break line numbers in crashes.
I forked 1.0.1 to keep line numbers with my report to show code causing crash.
## Crash 1 (fixed in #681)

[line 425](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L425)
Multiple crashes there. I modified function:

``` javascript
  function onError (event) { console.log('Inspect: ' + require('util').inspect(event));
    event.type = 'error';
    event.target = target;
    listener.call(target, event);
  }
```

No crashes:

```
Inspect: [Error: Connection Timed Out]
Inspect: [Error: Socket Closed]
```

Crashes:

```
Inspect: 'reserved fields must be empty'
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:195:12)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

```
Inspect: 'no handler for opcode 11'
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of no handler for opcode 11
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:234:43)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

```
Inspect: 'no handler for opcode 3'
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of no handler for opcode 3
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:234:43)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

```
Inspect: 'no handler for opcode 5'
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of no handler for opcode 5
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:234:43)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

```
Inspect: 'continuation frame cannot follow current opcode'
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:212:12)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

There may be other but waiting for crashes is so slow and boring.
Disabled them for debugging

``` javascript
  function onError (event) { 
    try { event.type = 'error'; }catch(e){}
    try { event.target = target; }catch(e){} //this one will crash too
    listener.call(target, event);
  }
```
## Crash 2

[line 216](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L216)

```
D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:218
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:218:16)
    at Object.Client.send (D:\Projects\agario-investigation\node_modules\agario-client\agario-client.js:177:17)
    at Object.Client.onConnect (D:\Projects\agario-investigation\node_modules\agario-client\agario-client.js:90:14)
    at WebSocket.onOpen (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:432:14)
    at WebSocket.emit (events.js:104:17)
    at WebSocket.establishConnection (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:862:8)
    at ClientRequest.upgrade (D:\Projects\agario-investigation\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:753:25)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:118:17)
    at Socket.socketOnData (_http_client.js:349:11)
```

Caused by my code at [line 90](https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L90) but this code is called by listener `ws.onopen` in [line 49](https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L49)
So looks like when <b>ws</b> calls `onopen` the `this.readyState` is not `WebSocket.OPEN` somehow. 
I am not sure if this is problem in <b>ws</b>. 
I think `readyState` should be `OPEN` on `onopen` event. I may be wrong, tell me if i am.
To trace changes of `readyState` i added `this.state_change_log = [];` in [line 67](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L67)
And `WebSocket.prototype.logChangedState = function(line, old_state, new_state) { if(this.state_change_log.length > 10) this.state_change_log.shift(); this.state_change_log.push([line, old_state, new_state]);` in [line 93](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L93)

[line 104](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L104) 
`this.logChangedState(104, this.readyState, WebSocket.CLOSED); this.readyState = WebSocket.CLOSED;`
[line 117](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L117) 
`this.logChangedState(117, this.readyState, WebSocket.CLOSING); this.readyState = WebSocket.CLOSING;`
[line 336](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L336) 
`this.logChangedState(336, this.readyState, WebSocket.CLOSING); this.readyState = WebSocket.CLOSING;`
[line 535](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L535) 
`this.logChangedState(535, this.readyState, WebSocket.CONNECTING); this.readyState = WebSocket.CONNECTING;`
[line 762](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L762) 
`this.logChangedState(762, this.readyState, WebSocket.CONNECTING); this.readyState = WebSocket.CONNECTING;`
[line 861](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L861)
`this.logChangedState(861, this.readyState, WebSocket.OPEN); this.readyState = WebSocket.OPEN;`
[line 915](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L915)
`this.logChangedState(915, this.readyState, WebSocket.CLOSED); this.readyState = WebSocket.CLOSED;`
[line 218](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L915)
`else { console.log(require('util').inspect(this.state_change_log)); throw new Error('not opened'); }`
Result:

```
[ [ 762, null, 0 ] ]
```

Somehow `onconnect` called with state `WebSocket.CONNECTING` that is set in [line 762](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L762). 
Not sure if this information is enough for fix.

For disable crash edited [line 218](https://github.com/pulviscriptor/ws/blob/master/lib/WebSocket.js#L915)
`else { /*console.log(require('util').inspect(this.state_change_log)); throw new Error('not opened');*/ this.close() }`

I thought there will be much more crashes, but no. Only those two places in code.
After my "fixes" no more crashes.

**Comment by pulviscriptor** [comment]
While i was experimenting here, i found that i can crash servers. Uhm...
server.js
```javascript
var WebSocketServer = require('ws').Server
    , wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function connection(ws) {
    ws.onerror = function(error) {
        console.log('onerror called');
    };
});
```
client.js
```javacript
var WebSocket = require('ws');
var socket = new WebSocket('ws://127.0.0.1:8080/');

socket.onopen = function() {
    console.log('onopen called');
    socket._socket.write(new Buffer([5]));
    socket.send('');
};

socket.onclose = function(event) {
    console.log('onclose called');
};

socket.onerror = function(error) {
    console.log('onerror called');
};
```
Server will crash
```
D:\Projects\agario-investigation\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of no handler for opcode 5
    at WebSocket.onError (D:\Projects\agario-investigation\node_modules\ws\lib\WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (D:\Projects\agario-investigation\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (D:\Projects\agario-investigation\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (D:\Projects\agario-investigation\node_modules\ws\lib\Receiver.js:234:43)
    at Receiver.add (D:\Projects\agario-investigation\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\Projects\agario-investigation\node_modules\ws\lib\WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by 3rd-Eden** [comment]
Does it continously crash or just randomly?

**Comment by pulviscriptor** [comment]
@3rd-Eden 
Crash 1 and Crash 2 is random. 
Server crash is reproducible by script that i posted, crashes every time.

**Comment by davidmann4** [comment]
:+1: have the same issue using his lib in /agario-feeder-bot/

**Comment by LordMajestros** [comment]
I have made a PR with a fix for the reproducible crash in the posted script but it is based off of https://github.com/websockets/ws/pull/681cc @3rd-Eden

**Comment by LordMajestros** [comment]
Please confirm that this PR https://github.com/websockets/ws/pull/681 fixes all these issues. I've been testing these and I haven't had any errors except Crash 2 Error: not opened which I think is expected behaviour when writing to a closed socket.

**Comment by pulviscriptor** [comment]
@LordMajestros
Running for about 10 hours, no crashes.

**Comment by LordMajestros** [comment]
Great news @pulviscriptor

**Comment by kevdude749** [comment]
This really helped! This is the fix that I was looking for. I had the "Websocket not opened" error and I thought that it was my code, but I guess it's an issue with the Websockets.js file...
