### ISSUE TITLE
Tests failing on 1.0.1 for mips, mipsel, mips64el

### ISSUE THREAD

**Issue by infinity0** [websockets/ws#677]
Hi, the tests are failing on multiple mips-architecture machines. Example failure:

```
[92m [0m[32m 256 passing[0m[90m (41s)[0m
[31m  3 failing[0m

[0m  1) WebSocketServer hixie mode connection establishing client can be accepted:
[0m[31m     Error: timeout of 5000ms exceeded[0m[90m
      at null.<anonymous> (/usr/lib/nodejs/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:92:15)
[0m
[0m  2) WebSocket #send very long binary data can be sent and received (with echoing server):
[0m[31m     Error: timeout of 5000ms exceeded[0m[90m
      at null.<anonymous> (/usr/lib/nodejs/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:92:15)
[0m
[0m  3) WebSocket ssl can send and receive very long binary data:
[0m[31m     Error: timeout of 5000ms exceeded[0m[90m
      at null.<anonymous> (/usr/lib/nodejs/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:92:15)
[0m
```

It seems the failule was introduced between 1.0.0 and 1.0.1 - see Debian buildd logs for [mips](https://buildd.debian.org/status/logs.php?pkg=node-ws&arch=mips) | [mipsel](https://buildd.debian.org/status/logs.php?pkg=node-ws&arch=mipsel) | [mips64el](https://buildd.debian.org/status/logs.php?pkg=node-ws&arch=mips64el).

If you have any specific ideas on how to debug this that would be useful; I can log into similar machines and test that out.

**Comment by lpinca** [comment]
@infinity0 can you try with the master branch?
Thanks.

**Comment by lpinca** [comment]
Closing due to inactivity.
