### ISSUE TITLE
unsupported binaryType "buffer"

### ISSUE THREAD

**Issue by joeysino** [websockets/ws#725]
We get this when running our unit tests against the latest version 1.1.0.  Curiously it only happens when we run all our tests together with `mocha`, and not when we run them individually.

```
 SyntaxError: unsupported binaryType: must be either "nodebuffer" or "arraybuffer"
  at WebSocket.set (node_modules/ws/lib/WebSocket.js:392:13)
  at WS.doOpen (node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:108:24)
  at WS.Transport.open (node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:78:10)
  at Socket.open (node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:230:13)
  at new Socket (node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:111:8)
  at Socket (node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:37:41)
  at Manager.open.Manager.connect (node_modules/socket.io-client/lib/manager.js:214:17)
  at new Manager (node_modules/socket.io-client/lib/manager.js:68:30)
  at Manager (node_modules/socket.io-client/lib/manager.js:37:42)
  at Function.lookup [as connect] (node_modules/socket.io-client/lib/index.js:56:10)
  at Object.socketConnection.connectSocket (test_modules/socketConnection.js:67:25)
  at Object.socketConnection.createConnection (test_modules/socketConnection.js:79:25)
  at Context.<anonymous> (test/testApiUser.js:35:26)
```

Logging showed that the type that was actually being passed to that function was "`buffer`".

Should I be filing this bug against `socket.io-client`?

**Comment by Nibbler999** [comment]
`engine.io-client` doesn't support ws 1.1.0 yet.

**Comment by zhirzh** [comment]
ok. I **was** getting the same error with my setup which is:

    node 4.4.5
    npm 3.9.5

    socket.io ^1.4.8
    socket.io-client ^1.4.8
    socket.io-stream ^0.9.0
    webpack ^1.13.1

I am using `webpack` to bind together the aforementioned socketio modules and the final config that worked for me is below:

    var path = require('path');
    var SRC_DIR = path.resolve(__dirname, 'src');
    var BUILD_DIR = path.resolve(__dirname, 'build');
    var NODE_DIR = path.resolve(__dirname, 'node_modules');
    module.exports = {
      entry: path.resolve(SRC_DIR, 'index'),
      target: 'node',
      output: {
        path: BUILD_DIR,
        filename: 'bundle.js',
        publicPath: '/'
      },
      module: {
        noParse: [/json-schema/],
        loaders: [{
          test: /\.jsx?$/,
          include: SRC_DIR,
          loader: 'babel-loader'
        }, {
          test: /\.json$/,
          loader: 'json-loader',
        }, {
          test: /\.scss$/,
          include: SRC_DIR,
          loaders: ['style-loader', 'css-loader', 'sass-loader']
        }]
      },
      resolve: {
        modulesDirectories: [SRC_DIR, NODE_DIR],
        extensions: ['', '.js', '.jsx', '.json']
      },
      externals: {
        'socket.io': 'commonjs socket.io',
        'socket.io-client': 'commonjs socket.io-client',
        'socket.io-stream': 'commonjs socket.io-stream',
      },
    };

**Comment by lpinca** [comment]
Closed as I think this is no longer an issue, please reopen if it's not the case.
