### ISSUE TITLE
Error when client tries to connect: SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by KronKraken** [websockets/ws#761]
Today I was trying to use my WS app, the server opens and all, people are able to connect but some seconds after it crashes throwing this error:

> events.js:141
>       throw er; // Unhandled 'error' event
> 
> Error: write EPROTO 101057795:error:14077458:SSL routines: SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name:openssl/ssl/s23_clnt.c:769:
> 
> at exports._errnoException (util.js:870:11)
> at WriteWrap.afterWrite (net.js:769:14)

Any ways to fix it?

**Comment by lpinca** [comment]
@KronKraken Is this still an issue?

**Comment by lpinca** [comment]
Closing due to inactivity.
