### ISSUE TITLE
Can't connect to server using socket.io

### ISSUE THREAD

**Issue by maxjoehnk** [websockets/ws#792]
Hi,
I'm using socket.io and socket.io-client for communication between two node instances.
The Client crashes while trying to connect which seems to be a problem with ws itself and not with socket.io.

Log:
```
/src/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of control frames cannot have the Per-message Compressed bits
    at WebSocket.onError (/src/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (/src/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/src/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/src/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:222:12)

    at Receiver.add (/src/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/src/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```

Server Code:
```javascript
    server = IO(http); //http.Server with express as request handler listening on 8080

    server.on('connection', (socket) => {
        debug(`Socket.IO Connection ${socket.id}`);
        
    });
```

Client Code:
```javascript
    debug(conn); //{"ip":"serverip", "port":8080}
    return Q.Promise((resolve, reject) => {
        socket = io(`http://${conn.ip}:${conn.port}`);
        debug('connecting');
        socket.once('connect', () => {
            debug('connected');
            resolve();
        });
        socket.once('connect_error', reject);
        socket.once('reconnect_failed', reject);
    });
```

The connection event is triggered on the server side but the client crashes before the connect event is emitted. The disconnect event isn't triggered on the server side though.

Now maybe I have done a mistake somewhere?
But the error message isn't 100% clear to me and i feel like it is a ws error.
Also the code was working yesterday, but when I revert my changes it's still not working.

The Promise isn't rejected btw, even though a thrown error in a promise should reject it.

**Comment by maxjoehnk** [comment]
Seems to be a problem that I'm using mqtt and socket.io with the same http server, not sure what exactly is causing it but I will close this issue.

**Comment by DSigmund** [comment]
I must reopen this, as i have the same error...
But i am not using mqtt, just some services using socket.io to send messages and one service, that catches them all and throws this error...
