### ISSUE TITLE
Cannot access wss.clients array

### ISSUE THREAD

**Issue by SonnyRajagopalan** [websockets/ws#800]
I have a nodejs v6.3.1 class for `ws` objects that looks like this (`WSS.js`):

    var EventEmitter = require ('events');
    var WebSocketServer = require('ws').Server;

    function WSS () {
      this.wss = new WebSocketServer ({port: 8088});
      this.cee = new EventEmitter ();
      this.wss.on ('connection', function (conn) {
        console.log ('New connection');
        //conn.send ('tickles');
        conn.on ('message', function (message) {
          console.log ('received: %s', message);
        });
      });
      this.cee.on('sendEvent', function (message) {
        for (var i=0, l = this.wss.clients.length; i < l; ++i) {
          this.wss.clients[i].send (message);
        }
        //this.wss.clients.forEach (function each (client) {
          //client.send (message);
        //});
      });
    }
    WSS.prototype.sendRequest = function send (message) {
      this.cee.emit ('sendEvent', message);
    }
    module.exports = WSS;

I use the module in my code in the following manner (`main.js`):

    var WSS = require ('./WSS.js');
    var http = require ('http');

    process.on('uncaughtException', function (err) {
      console.error(err);
      console.log("Node NOT Exiting...");
    });

    var wsserver = new WSS ();

    http.createServer (function handleRequest (req, res) {
      res.end('It Works!! Path Hit: ' + req.url + '\n');
        wsserver.sendRequest ('Hey, a new HTTP request');
    }).listen (8080);

I run the server like so:

    $ node main.js

I connect to the websocket server like so:

    $ wscat -c http://localhost:8088/

Which works, but I am not able to broadcast (`Hey, a new HTTP request`) does not get broadcast for the following error:

    TypeError: Cannot read property 'clients' of undefined
        at EventEmitter.<anonymous> (/full/path/WSS.js:15:31)
        at emitOne (events.js:96:13)
        at EventEmitter.emit (events.js:188:7)
        at WSS.send [as sendRequest] (/full/path/WSS.js:24:12)
        at Server.handleRequest (/full/path/main.js:13:14)
        at emitTwo (events.js:106:13)
        at Server.emit (events.js:191:7)
        at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

I am surprised because per the documentation, `this.wss.clients` contains all the `client` objects. Any insight is appreciated. Thanks!

**Comment by ericmdantas** [comment]
I'm guessing this:

```js
this.cee.on('sendEvent', function (message) {
    for (var i=0, l = this.wss.clients.length; i < l; ++i) {
      this.wss.clients[i].send (message);
    }
  });
```

Should be:

```js
 this.cee.on('sendEvent', function (message) {
    for (var i=0, l = this.wss.clients.length; i < l; ++i) {
      this.wss.clients[i].send (message);
    }
  }.bind(this));
```

Or:

```js
 this.cee.on('sendEvent', (message) => {
    for (var i=0, l = this.wss.clients.length; i < l; ++i) {
      this.wss.clients[i].send (message);
    }
  });
```

So you have the same `this`, in and out of the function.

**Comment by ericmdantas** [comment]
`bind` is all about javascript, it's not restrict to node. I suggest you search stuff like `arrow functions`, `bind vs call`, etc.
