### ISSUE TITLE
how to handle proxy timeout 

### ISSUE THREAD

**Issue by aryeharmon** [websockets/ws#825]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 39.1.42.166:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

```

**Comment by JoshuaWise** [comment]
try `Websocket#ping()`, which sends a heartbeat signal to the opposite endpoint. Because it's on the WebSocket layer, it survives through TCP proxies.

**Comment by aryeharmon** [comment]
All i needed to do is add an error handler
```
socket.on('error', function (err) {
	console.log(err);
});
```

**Comment by JoshuaWise** [comment]
Ahh, sorry, I misinterpreted your question. You are correct.
