### ISSUE TITLE
Unhandled rejection Error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

### ISSUE THREAD

**Issue by aryeharmon** [websockets/ws#830]
i get this error every so often.
i have an error callback but it still does not get to it. 

```

Unhandled rejection Error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
    at Error (native)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at WebSocket.initAsClient (/home/aryeh/Code/proxy/node_modules/ws/lib/WebSocket.js:621:23)
    at new WebSocket (/home/aryeh/Code/proxy/node_modules/ws/lib/WebSocket.js:79:18)
    at Object.proxy_tester.socket_test (/home/aryeh/Code/proxy/inc/proxy_tester.js:161:16)
    at proxy_tester.test_ws (/home/aryeh/Code/proxy/inc/proxy_tester.js:124:8)
    at nextTask (/home/aryeh/Code/proxy/node_modules/async/dist/async.js:5021:18)
    at /home/aryeh/Code/proxy/node_modules/async/dist/async.js:5015:17
    at /home/aryeh/Code/proxy/node_modules/async/dist/async.js:339:31
    at /home/aryeh/Code/proxy/node_modules/async/dist/async.js:847:20
    at /home/aryeh/Code/proxy/inc/proxy_tester.js:115:4
    at tryCatcher (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/aryeh/Code/proxy/node_modules/check-proxy/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by aryeharmon** [comment]
seems like this is only happening on some servers. any ideas?

**Comment by lpinca** [comment]
@aryeharmon is this still an issue?

**Comment by lpinca** [comment]
Closing due to inactivity.
