### ISSUE TITLE
TypeError: Cannot call method 'close' of null

### ISSUE THREAD

**Issue by tixastronauta** [websockets/ws#838]
The following error crashed my WebSocket server when I was reaching ~12000 active connections.

```
TypeError: Cannot call method 'close' of null
    at InflateRaw.Zlib.close (zlib.js:363:17)
    at PerMessageDeflate.cleanup (/my/project/node_modules/ws/lib/PerMessageDeflate.js:83:46)
    at WebSocket.cleanupWebsocketResources (/my/project/node_modules/ws/lib/WebSocket.js:979:54)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
```

Any tip on how to avoid this?

**Comment by lpinca** [comment]
It seems that this issue has been fixed by this commit https://github.com/nodejs/node/commit/b53473f0e7eab68e4bc844474f286d834cbc6fc0.

**Comment by lpinca** [comment]
The fix has not been backported to node 4.
