### ISSUE TITLE
"Error: invalid error code" in WS

### ISSUE THREAD

**Issue by zaksmok** [websockets/ws#852]
Hello. From time to time my app crashes with error like this:

`Error: invalid error code
    at Receiver.error (/home/server/node_modules/ws/lib/Receiver.js:321:18)
    at /home/server/node_modules/ws/lib/Receiver.js:683:16
    at Receiver.flush (/home/server/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/server/node_modules/ws/lib/Receiver.js:698:12)
    at Receiver.<anonymous> (/home/server/node_modules/ws/lib/Receiver.js:661:33)
    at Receiver.add (/home/server/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/server/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
`

Any suggestions what can I do?

**Comment by lpinca** [comment]
Looks like you are receiving an invalid error [code](https://github.com/websockets/ws/blob/c7bb7306cb0e1d17df141f61a220056eaa5e3502/lib/ErrorCodes.js#L8-L11).
Anyway it shouldn't crash your app if you add an `error` handler:

```js
wss.on('connection', (ws) => {
  ws.on('error', (err) => { // Do something with the error. });
});
```

**Comment by semiromid** [comment]
Hi, lpinca. I get it error if i use browser on Android Opera 24.0. 1565.82529

**Comment by semiromid** [comment]
I get 
```
             ws.on('error', (err) => {
              // Handle the error.
              console.log('Ошибка');
              console.log(err.code);
              
              console.log(util.inspect(err, false, null));
            });
```

undefined
[Error: invalid error code]

**Comment by semiromid** [comment]
If i remove - ` ws.on('error', (err).......`



```
events.js:154
      throw er; // Unhandled 'error' event
      ^


Error: invalid error code
    at Receiver.error (E:\Developers\WebDeveloper\OpenServer-WebProg\domains\ws-
nodejs\node_modules\ws\lib\Receiver.js:321:18)
    at E:\Developers\WebDeveloper\OpenServer-WebProg\domains\ws-nodejs\node_modu
les\ws\lib\Receiver.js:683:16
    at Receiver.flush (E:\Developers\WebDeveloper\OpenServer-WebProg\domains\ws-
nodejs\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.8.finish (E:\Developers\WebDeveloper\OpenServer-WebProg\
domains\ws-nodejs\node_modules\ws\lib\Receiver.js:698:12)
    at Receiver.<anonymous> (E:\Developers\WebDeveloper\OpenServer-WebProg\domai
ns\ws-nodejs\node_modules\ws\lib\Receiver.js:661:33)
    at Receiver.add (E:\Developers\WebDeveloper\OpenServer-WebProg\domains\ws-no
dejs\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (E:\Developers\WebDeveloper\OpenServer-WebProg\domains
\ws-nodejs\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

**Comment by lpinca** [comment]
Yes, removing error handlers is not a good idea.
Anyway, it seems that client sends an invalid code https://github.com/websockets/ws/blob/c7bb7306cb0e1d17df141f61a220056eaa5e3502/lib/Receiver.js#L682-L685?
