### ISSUE TITLE
Multiple client connections to same server causes crash

### ISSUE THREAD

**Issue by timofverberg** [websockets/ws#887]
When connecting more than one socket, I get an instant crash.
Minimal code:
```
var WebSocket = require('ws');
var socket1 = new WebSocket('ws://localhost:5555')
var socket2 = new WebSocket('ws://localhost:5555')
```
Error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The server used is a custom ws server, not the one included.
Does this have anything to do with #684 ?
@LordMajestros noted that "existing connections are reused when connecting to the same server".
And the solution is to "force new connection"
But I can't find any reference to this in the code or docs...

**Comment by lpinca** [comment]
"force new connection" is a Socket.IO option which has nothing to do with `ws`.

I can't reproduce the issue. This code works fine:

```js
'use strict';

const WebSocket = require('ws');

const ws1 = new WebSocket('ws://echo.websocket.org');
const ws2 = new WebSocket('ws://echo.websocket.org');

ws1.on('open', () => console.log('client 1 connected'));
ws2.on('open', () => console.log('client 2 connected'));
```

**Comment by timofverberg** [comment]
Neither can I. Closing!
