### ISSUE TITLE
err: WebSocketServer is not defined

### ISSUE THREAD

**Issue by eliezergu** [websockets/ws#904]
Hi I tried to run the example for ws with express but node throw err: WebSocketServer is not defined, here is my code >>>

 `'use strict';
var server = require('https');
var fs = require('fs');

var privateKey = fs.readFileSync('<<my-path>>', 'utf8');
var certificate = fs.readFileSync('<<my-path>>', 'utf8');

var credentials = {key: privateKey, cert: certificate};

server.createServer(credentials, app);

var url = require('url');
var webSocketServer = require('ws').Server;

var wss = new WebSocketServer({server: server});
var express = require('express');
var app = express();
var port = 8443;

app.use(function (req, res) {
    res.send({msg: 'Hello'});
});

wss.on('connection', function connection(ws) {
    var location = url.parse(ws.upgradeReq.url, true);
    
ws.on('message', function incoming(message) {
    console.log('received: %s', message);
});
    
ws.send('Thanks for message');    
});

server.on('request', app);
server.listen(port, function () {
    console.log('Listening on ' + server.address().port);
});`

**Here is the node err:>>>** 

C:\Users\shulem\Documents\myWebRTCApp>node expressWS.js
C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18
var wss = new WebSocketServer({server: server});
              ^

ReferenceError: WebSocketServer is not defined
    at Object.<anonymous> (C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**BTW I tried** `var wss new webSocketServer` **With a small w and i got the following err: >>>**

C:\Users\shulem\Documents\myWebRTCApp>node expressWS.js
C:\Users\shulem\Documents\myWebRTCApp\node_modules\ws\lib\WebSocketServer.js:78
    this._server.once('listening', this._onceServerListening);
                 ^

TypeError: this._server.once is not a function
    at new WebSocketServer (C:\Users\shulem\Documents\myWebRTCApp\node_modules\ws\lib\WebSocketServer.js:78:18)
    at Object.<anonymous> (C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

Any suggestions?

**Comment by lpinca** [comment]
Change this line

```js
var server = require('https');
```
to

```js
var https = require('https')`
```

and 

```js
server.createServer(credentials, app);
```
to

```js
var server = https.createServer(credentials, app);
```

**Comment by eliezergu** [comment]
Thanks for answering I followed your instructions and now i'm getting a new err

C:\Users\shulem\Documents\myWebRTCApp>node expressWS.js
C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18
var wss = new WebSocketServer({server: server});
                                       ^

ReferenceError: server is not defined
    at Object.<anonymous> (C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Please let me know your suggestions thanks for your help 
(BTW: I tried to change  `var wss = new WebSocketServer({server: server});` to `var wss = new WebSocketServer({server: https});`
But than i got the second err i mentioned in the issue)

**Comment by lpinca** [comment]
Put your file in a https://gist.github.com/ and post the link to the gist here.
Thanks.

**Comment by eliezergu** [comment]
Thanks I figured it out already 
https://gist.github.com/eliezergu/d13201dd26413a4ed211c0b1f6c9bceb

**Comment by lpinca** [comment]
Ok, thanks.
I close this issue then. Please comment if you still need help.
