### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by bdunn44** [websockets/ws#949]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Error encountered when establishing a socket.io connection, which crashes Node. Posting the issue here because it seems to be a ws issue.

### Steps to reproduce (if the current behaviour is a bug)
    io.on('connection', (socket) => {
      // Listen for verification subscription requests
      log.debug("Established socket connection " + socket.id);
      socket.on('verify subscribe', (msg) => {
        log.debug("Recieved 'verify subscribe' message: " + JSON.stringify(msg));
        // Do stuff....
      });
    });

This code outputs the following log messages prior to the error:

    [2016-12-30T19:08:09.219Z] DEBUG: Established socket connection -g9oZM6pEqpFyU_BAAAA
    [2016-12-30T19:08:09.275Z] DEBUG: Recieved 'verify subscribe' message: {"token":"short-ish.token","authorization":"long.auth-token"}

### Expected behaviour
Successful socket connection without crash.

### Setup
 - OS: Windows 7 
 - Node: 6.9.2
 - NPM: 4.0.5
 - Packages:
   - "express": "^4.14.0"
   - "socket.io": "1.7.1"
   - "socket.io-client": "1.7.1"
   - "ws": "1.1.1"

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
    TypeError: Cannot read property 'on' of undefined
        at PerMessageDeflate.decompress (C:\ng-project\node_modules\ws\lib\PerMessageDeflate.js:242:37)
        at Receiver.applyExtensions (C:\ng-project\node_modules\ws\lib\Receiver.js:362:54)
        at C:\ng-project\node_modules\ws\lib\Receiver.js:508:14
        at Receiver.flush (C:\ng-project\node_modules\ws\lib\Receiver.js:347:3)
        at Receiver.opcodes.1.finish (C:\ng-project\node_modules\ws\lib\Receiver.js:541:12)
        at Receiver.expectHandler (C:\ng-project\node_modules\ws\lib\Receiver.js:493:33)
        at Receiver.add (C:\ng-project\node_modules\ws\lib\Receiver.js:103:24)
        at Socket.realHandler (C:\ng-project\node_modules\ws\lib\WebSocket.js:825:20)
        at ZoneDelegate.invokeTask (C:\ng-project\node_modules\zone.js\dist\zone-node.js:265:35)
        at Zone.runTask (C:\ng-project\node_modules\zone.js\dist\zone-node.js:154:47)
        at Socket.ZoneTask.invoke (C:\ng-project\node_modules\zone.js\dist\zone-node.js:335:33)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:177:18)
        at Socket.Readable.push (_stream_readable.js:135:10)
        at TCP.onread (net.js:542:20)

Looking into the `ws` module I can see the line of code throwing the error:

    this._inflate.on('error', onError).on('data', onData);

`_inflate` is a zlib `InflateRaw` instance created by `zlib.createInflateRaw({...})` a few lines earlier. The problem is that the `InflateRaw#on` function returns `undefined` in my environment.

I have tried installing alternate versions of Node to work around this without any luck... Altering the `ws` package is not an acceptable workaround for me.

**Comment by bdunn44** [comment]
Also posted to SO: http://stackoverflow.com/questions/41401360/node-js-socket-io-cannot-read-property-on-of-undefined

**Comment by Nibbler999** [comment]
Looks like a zone.js issue - angular/zone.js/issues/508

**Comment by lpinca** [comment]
Updating that dep should fix the issue, closing.

**Comment by bdunn44** [comment]
Thanks Nibbler, that fix should solve my problem. Unfortunately the latest zone.js release has another issue (angular/zone.js#574) which breaks another project dependency, so I'm in limbo at the moment.
