### ISSUE TITLE
Exception "Unhandled 'error' event"

### ISSUE THREAD

**Issue by duselguy** [websockets/ws#958]
Hello,
the code below:
`const server = require('http').createServer();
const WebSocketServer = require('ws').Server;

//const socket = new WebSocketServer({ server: server });

server.listen(3000, '128.0.0.1').on('error', function (err) {
    console.log('Server listen failed: ' + err.code);
});`
works ok with output: Server listen failed: EADDRNOTAVAIL
If to uncomment the line above:
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRNOTAVAIL 128.0.0.1:3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
Thanks,
LP
P.S. Sorry I'm newbie in JS.

**Comment by lpinca** [comment]
@duselguy it works as expected. The address is not valid so an error is emitted. If there is no `error` listener the error is thrown.

**Comment by duselguy** [comment]
Thanks a lot,
LP
