### ISSUE TITLE
browserify --node fails because peer modules are required (bufferutil, utf-8-validate)

### ISSUE THREAD

**Issue by gabssnake** [websockets/ws#985]
Hello, thank you for your work with this project!

While not using the compiled optional modules and using `browserify --node` to concatenate files, I get the following message :

```
> browserify --node --entry index.js

Error: Cannot find module 'bufferutil' from '/project/node_modules/ws/lib'
    at /project/node_modules/resolve/lib/async.js:47:17
    at process (/project/node_modules/resolve/lib/async.js:174:43)
    at ondir (/project/node_modules/resolve/lib/async.js:189:17)
    at load (/project/node_modules/resolve/lib/async.js:70:43)
    at onex (/project/node_modules/resolve/lib/async.js:93:31)
    at /project/node_modules/resolve/lib/async.js:23:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

`lib/BufferUtil.jsL9` tries to load the module like this : 
```
try {
  module.exports = require('bufferutil');
} catch (e) {
  module.exports = require('./BufferUtil.fallback');
}
```

The following workaround worked in my case (tell browserify to ignore the modules):
```
> browserify --node --external bufferutil --external utf-8-validate --entry index.js
```

**Comment by lpinca** [comment]
You can probably tell browserify to exclude those module from the bundle.

**Comment by lpinca** [comment]
Closing, please comment or reopen if needed.
