### ISSUE TITLE
PerMessageDeflate Error

### ISSUE THREAD

**Issue by mtvbrianking** [websockets/ws#998]
I keep running into this error whenever I import ws
`const WebSocket = require('ws');`
Output
```
/home/brian/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/brian/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/brian/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
```

**Comment by lpinca** [comment]
What version of Node.js are you using?

**Comment by DiegoRBaquero** [comment]
@lpinca I think it's v6+

https://github.com/feross/webtorrent-hybrid/issues/62#issuecomment-279370267

http://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha/36924697#36924697

**Comment by lpinca** [comment]
@DiegoRBaquero it was backported and it is available in Node.js 4.5.0 or greater.

**Comment by DiegoRBaquero** [comment]
@lpinca Seems right, worked on 4.7

Thanks for the info!
